import { chromium } from 'playwright';
import { createLogger } from '../utils/logger';

const logger = createLogger({ service: 'html-renderer' });

export interface RenderParams {
  /** The raw background image buffer generated by the AI image generator */
  baseImageBuffer: Buffer;
  
  /** The brand logo URL (or empty string/fallback) */
  brandLogoUrl: string;

  /** Optional brand name to display in the header (defaults to campaign companyName / name / industry) */
  brandName?: string;

  /** Optional creative layout template style */
  templateStyle?: string;

  /** Optional transparent foreground subject mask URL (for 3D Typography Sandwiching) */
  subjectMaskUrl?: string;
  
  /** Ad headline text */
  headline: string;
  
  /** Ad subtitle/body description */
  subtitle: string;
  
  /** Call-to-action button text */
  cta: string;
  
  /** Target text overlay quadrant ('top_left' | 'top_right' | 'bottom_left' | 'bottom_right') */
  quadrant: string;
  
  /** Solved contrast and opacity metrics from localized color analysis */
  colors: {
    headlineColor: string;
    subtitleColor: string;
    isDarkBg: boolean;
    bgOpacityOverride: number;
    lightDirection?: {
      horizontal: number;
      vertical: number;
    };
  };

  /** Structured copy elements from the Copy Director */
  copyElements?: Array<{
    type: 'feature' | 'quote' | 'statistic' | 'badge' | 'paragraph' | 'cta';
    text: string;
    icon?: string;
    iconName?: string;
    value?: string;
  }>;
  
  /** Output viewport width in pixels (default: 1080) */
  width?: number;
  
  /** Output viewport height in pixels (default: 1080) */
  height?: number;

  /** Optional custom design overrides solved by second-pass Layout Director */
  layoutBlueprint?: {
    designArchetype?: string;
    layoutType?: 'classic' | 'feature_list' | 'editorial_column' | 'split_screen' | 'liquid';
    requireGlassmorphism?: boolean;
    fontFamily?: string;
    subtitleFontFamily?: string;
    headlineWeight?: 'black' | 'bold' | 'semibold' | 'medium';
    fontSizeScale?: number;
    containerPadding?: 'p-6' | 'p-8' | 'p-10' | 'p-12';
    backgroundColorOverride?: string;
    textColorOverride?: string;
    headlineColorOverride?: string;
    subtitleColorOverride?: string;
    accentColorOverride?: string;
    ctaBackgroundColorOverride?: string;
    ctaTextColorOverride?: string;
    badgeStyle?: 'translucent' | 'solid' | 'double_ring';
    ctaIconStyle?: 'none' | 'inline' | 'circular_arrow';
    useScriptHighlight?: boolean;
    features?: string[];
    dynamicHtmlBlock?: string;
    typographyZIndex?: 'behind' | 'in_front';
    
    // Dynamic Slide overrides
    slideHeader?: string;
    slideHighlight?: string;
    slideSub?: string;
    slideText?: string;
  };
  
  /** The slide index for carousel posts (0 = cover, 1 = features, 2 = benefits, 3 = CTA) */
  slideIndex?: number;

  /** Brand base color hex code */
  brandColor?: string;

  /** Brand accent color hex code */
  accentColor?: string;

  /** Target campaign geography */
  geography?: string;

  /** Target campaign industry/niche */
  industry?: string;

  /** Dynamic topic / post theme */
  topic?: string;
}


/**
 * Smart dynamic Google Font param formatter.
 * Formats display fonts differently from body/paragraph text fonts.
 */
function formatGoogleFontParam(font: string): string {
  const cleaned = font.trim().toLowerCase();
  const displayFonts = new Set([
    'luckiest guy', 'lobster', 'bungee', 'plaster', 'alfa slab one', 
    'diplomata', 'averia sans libre', 'bebas neue', 'anton', 
    'archivo black', 'cinzel', 'syne', 'diplomata sc', 'lobster two',
    'caveat', 'pacifico'
  ]);
  const fontParam = font.replace(/ /g, '+');
  
  let isDisplay = displayFonts.has(cleaned);
  for (const df of displayFonts) {
    if (cleaned.includes(df)) {
      isDisplay = true;
      break;
    }
  }
  
  if (isDisplay) {
    return `family=${fontParam}`;
  } else {
    return `family=${fontParam}:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900`;
  }
}

/**
 * Returns generic CSS font class fallbacks ('serif' | 'cursive' | 'sans-serif')
 */
function getFontFallback(fontName: string): 'serif' | 'cursive' | 'sans-serif' {
  if (!fontName) return 'sans-serif';
  const cleaned = fontName.toLowerCase();
  
  const cursiveKeywords = ['lobster', 'luckiest guy', 'handwritten', 'script', 'caveat', 'pacifico'];
  if (cursiveKeywords.some(k => cleaned.includes(k))) return 'cursive';
  
  const serifKeywords = [
    'serif', 'garamond', 'prata', 'lora', 'fraunces', 'editorial', 
    'merriweather', 'playfair', 'times', 'georgia', 'cormorant', 
    'biorhyme', 'arvo', 'cardo', 'spectral', 'cinzel', 'libre baskerville',
    'eb garamond', 'domine', 'dm serif', 'quattrocento', 'alegreya', 'diplomata', 'abril'
  ];
  if (serifKeywords.some(k => cleaned.includes(k))) return 'serif';
  
  return 'sans-serif';
}

/**
 * Resolves checkmark checklist bullet lists from post copy or blueprint.
 */
function resolveFeatureList(caption: string, headline: string, blueprintFeatures?: string[]): string[] {
  if (blueprintFeatures && blueprintFeatures.length > 0) return blueprintFeatures;
  
  const bulletLines = (caption || '')
    .split('\n')
    .map(line => line.trim())
    .filter(line => {
      const lower = line.toLowerCase();
      return (
        line.startsWith('•') ||
        line.startsWith('-') ||
        line.startsWith('*') ||
        line.startsWith('✓') ||
        line.startsWith('✗') ||
        lower.startsWith('check:') ||
        lower.startsWith('yes:') ||
        lower.startsWith('no:') ||
        lower.startsWith('bad:') ||
        lower.startsWith('good:')
      );
    });
    
  if (bulletLines.length > 0) {
    return bulletLines.map(line => line.replace(/^[•\-\*✓✗]\s*/, '').trim()).slice(0, 4);
  }
  
  // Try comma-separated chunks in description
  const commaSplit = (caption || '').split(',').map(s => s.trim()).filter(s => s.length > 1 && s.length < 35);
  if (commaSplit.length >= 2) {
    return commaSplit.slice(0, 4);
  }
  
  // No fallback — only display features when the LLM explicitly extracts them from the actual caption
  return [];
}

interface ParsedFeature {
  icon: string;
  text: string;
  isNegative: boolean;
  isEmoji: boolean;
}

/**
 * Smart parses a feature string to extract context-specific visual badges/emojis
 * and filter clean feature copywriting.
 */
function parseFeature(feat: string): ParsedFeature {
  // 1. Strip generic checklist prefixes, standard ticks/crosses, or bullet marks first
  const cleaned = feat.trim().replace(/^([✓✗✕\-\*•\s]|check:|yes:|good:|no:|bad:|cross:)+/i, '').trim();

  let text = cleaned;
  let icon = '';
  let isNegative = false;
  let isEmoji = false;

  // 2. Detect Unicode Extended Pictographics (Emojis) at the very start of cleaned text
  const emojiMatch = cleaned.match(/^(\p{Extended_Pictographic})/u);
  if (emojiMatch) {
    icon = emojiMatch[1];
    isEmoji = true;
    text = cleaned.substring(icon.length).trim();
    
    // Check if the emoji represents a negative or caution cue
    const negativeEmojis = ['🚫', '❌', '👎', '⛔', '🚷', '🛑'];
    const lowerText = text.toLowerCase();
    isNegative = negativeEmojis.includes(icon) || 
                 lowerText.startsWith('no ') || 
                 lowerText.startsWith('zero ') || 
                 lowerText.startsWith('free of ') || 
                 lowerText.startsWith('without ');
  } else {
    // 3. Fallback: Determine icon and negativity based on original text cues
    const lowerText = feat.toLowerCase();
    isNegative = lowerText.includes('no ') || 
                 lowerText.includes('zero ') || 
                 lowerText.includes('free of ') || 
                 lowerText.includes('without ') ||
                 lowerText.includes('✗') ||
                 lowerText.includes('✕');
    icon = isNegative ? '✕' : '✓';
  }

  // Strip any remaining unwanted symbols from the start of cleaned text
  text = text.replace(/^[:\-\s\•\*✓✗✕]+/i, '').trim();

  return { icon, text, isNegative, isEmoji };
}

/**
 * Renders a premium circular icon badge using Lucide SVG icons.
 * Falls back to emoji or checkmark if no iconName is provided.
 */
function renderIconBadge(params: {
  iconName?: string;
  emoji?: string;
  isNegative?: boolean;
  accentColor: string;
  isDarkBg: boolean;
  size?: number; // badge diameter in px, default 36
  badgeStyle?: 'translucent' | 'solid' | 'double_ring';
}): string {
  const { iconName, emoji, isNegative, accentColor, isDarkBg, size = 36, badgeStyle = 'translucent' } = params;
  const iconSize = Math.round(size * 0.5);
  
  // Determine badge colors based on style choice
  let bgColor = '';
  let borderColor = '';
  let iconColor = '';
  
  if (badgeStyle === 'solid') {
    bgColor = isNegative ? '#EF4444' : accentColor;
    borderColor = 'transparent';
    iconColor = '#FFFFFF';
  } else if (badgeStyle === 'double_ring') {
    bgColor = 'transparent';
    borderColor = isNegative ? 'rgba(239, 68, 68, 0.4)' : `${accentColor}50`;
    iconColor = isNegative ? '#EF4444' : accentColor;
  } else {
    // translucent / fallback
    bgColor = isNegative
      ? 'rgba(239, 68, 68, 0.15)'  // soft red
      : isDarkBg
        ? `${accentColor}22`       // accent with 13% opacity on dark
        : `${accentColor}18`;      // accent with 9% opacity on light
    
    borderColor = isNegative
      ? 'rgba(239, 68, 68, 0.25)'
      : isDarkBg
        ? `${accentColor}40`       // accent with 25% opacity
        : `${accentColor}30`;
    iconColor = isNegative ? '#EF4444' : accentColor;
  }
  
  if (badgeStyle === 'double_ring') {
    const outerSize = size;
    const innerSize = size - 6; // slightly smaller inner circle
    const innerIconSize = Math.round(innerSize * 0.55);
    const innerBorderColor = isNegative ? 'rgba(239, 68, 68, 0.6)' : `${accentColor}80`;
    
    let innerContent = '';
    if (iconName) {
      innerContent = `<i data-lucide='${iconName}' style='width: ${innerIconSize}px; height: ${innerIconSize}px; color: ${iconColor}; stroke-width: 1.5;'></i>`;
    } else if (emoji) {
      innerContent = `<span style='font-size: ${innerIconSize}px; line-height: 1;'>${emoji}</span>`;
    } else {
      const symbol = isNegative ? '✕' : '✓';
      innerContent = `<span style='color: ${iconColor}; font-weight: 900; font-size: 11px;'>${symbol}</span>`;
    }
    
    return `<div style='display: flex !important; align-items: center !important; justify-content: center !important; flex-shrink: 0 !important; width: ${outerSize}px !important; height: ${outerSize}px !important; border-radius: 50% !important; border: 1.5px solid ${borderColor}; background: transparent;'>
      <div style='display: flex !important; align-items: center !important; justify-content: center !important; width: ${innerSize}px !important; height: ${innerSize}px !important; border-radius: 50% !important; border: 1px solid ${innerBorderColor}; background: transparent;'>
        ${innerContent}
      </div>
    </div>`;
  }
  
  if (iconName) {
    // Lucide SVG icon badge
    return `<div style='display: flex !important; align-items: center !important; justify-content: center !important; flex-shrink: 0 !important; width: ${size}px !important; height: ${size}px !important; border-radius: 50% !important; background: ${bgColor}; border: 1px solid ${borderColor};'>
      <i data-lucide='${iconName}' style='width: ${iconSize}px; height: ${iconSize}px; color: ${iconColor}; stroke-width: 2;'></i>
    </div>`;
  } else if (emoji) {
    // Emoji badge
    return `<div style='display: flex !important; align-items: center !important; justify-content: center !important; flex-shrink: 0 !important; width: ${size}px !important; height: ${size}px !important; border-radius: 50% !important; background: ${bgColor}; border: 1px solid ${borderColor};'>
      <span style='font-size: ${iconSize}px; line-height: 1; color: ${iconColor};'>${emoji}</span>
    </div>`;
  } else {
    // Fallback checkmark/cross
    const symbol = isNegative ? '✕' : '✓';
    return `<div style='display: flex !important; align-items: center !important; justify-content: center !important; flex-shrink: 0 !important; width: ${size}px !important; height: ${size}px !important; border-radius: 50% !important; background: ${bgColor}; border: 1px solid ${borderColor}; color: ${iconColor}; font-weight: 900; font-size: 14px;'>
      ${symbol}
    </div>`;
  }
}

/**
 * Renders a premium statistics grid block from CopyBlueprint statistic elements.
 * Creates a horizontal row of large-number-small-label metric cards.
 */
function renderStatisticsBlock(params: {
  stats: Array<{ value: string; text: string; iconName?: string }>;
  accentColor: string;
  headlineColor: string;
  subtitleColor: string;
  headlineFont: string;
  subtitleFont: string;
  isDarkBg: boolean;
}): string {
  if (params.stats.length === 0) return '';
  
  const { accentColor, headlineColor, subtitleColor, headlineFont, subtitleFont, isDarkBg } = params;
  
  const statItems = params.stats.slice(0, 3).map(stat => {
    const iconHtml = stat.iconName
      ? `<i data-lucide='${stat.iconName}' style='width: 18px; height: 18px; color: ${accentColor}; margin-bottom: 8px;'></i>`
      : '';
    
    return `
      <div style='display: flex; flex-direction: column; align-items: center; text-align: center; flex: 1; padding: 16px 8px;'>
        ${iconHtml}
        <div style='font-family: ${headlineFont}, sans-serif; font-size: 2.5rem; font-weight: 900; line-height: 1; color: ${accentColor}; letter-spacing: -0.02em;'>
          ${stat.value}
        </div>
        <div style='font-family: ${subtitleFont}, sans-serif; font-size: 0.75rem; font-weight: 600; color: ${subtitleColor}; margin-top: 6px; text-transform: uppercase; letter-spacing: 0.08em; opacity: 0.85;'>
          ${stat.text}
        </div>
      </div>
    `;
  }).join(`<div style='width: 1px; background: ${isDarkBg ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.08)'}; align-self: stretch; margin: 8px 0;'></div>`);
  
  return `
    <div style='display: flex; flex-direction: row; align-items: stretch; justify-content: center; width: 100%; margin-top: 12px; padding: 8px 0; border-radius: 16px; background: ${isDarkBg ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.03)'}; border: 1px solid ${isDarkBg ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)'};'>
      ${statItems}
    </div>
  `;
}

/**
 * Headless compositor that renders multi-layered premium ad creatives using Playwright.
 * Supports smart dynamic Google Fonts and four creative layout structures (classic, feature_list, comparison, editorial).
 */
export async function renderAdComposite({
  baseImageBuffer,
  brandLogoUrl,
  brandName,
  templateStyle: passedTemplateStyle,
  subjectMaskUrl,
  headline,
  subtitle,
  cta: rawCta,
  quadrant,
  colors,
  width = 1080,
  height = 1080,
  layoutBlueprint,
  slideIndex,
  brandColor: brandBaseColor,
  accentColor: brandAccentColor,
  geography: brandGeography,
  industry,
  topic,
  copyElements,
}: RenderParams): Promise<Buffer> {
  logger.info(`Launching Playwright headless compositor for resolution ${width}x${height}...`);
  if (subjectMaskUrl) {
    logger.info(`3D Subject overlay sandwich active. Mask URL: ${subjectMaskUrl}`);
  }

  const browser = await chromium.launch({ headless: true });
  
  try {
    const page = await browser.newPage();
    await page.setViewportSize({ width, height });

    // 1. Resolve Layout Director parameters
    const bp = layoutBlueprint || {};
    const slideIdx = slideIndex !== undefined ? slideIndex : 0;

    // Enforce CTA max length — truncate to 5 words + arrow if the LLM wrote a full sentence
    const truncateCta = (text: string): string => {
      const stripped = text.replace(/\s*[→➜»>]+\s*$/, '').trim();
      const words = stripped.split(/\s+/);
      if (words.length <= 5) return text; // already short enough
      return words.slice(0, 5).join(' ') + ' →';
    };
    const cta = truncateCta(rawCta);
    
    // Check template style & layout type
    const templateStyle = passedTemplateStyle || bp.designArchetype || 'glassmorphism';
    const layoutType = bp.layoutType || 'classic';
    const finalQuadrant = quadrant;
    
    // Improve Fallbacks: use semantic keyword matching since templateStyle is now free-form
    const styleLower = templateStyle.toLowerCase();
    const isGlass = styleLower.includes('glass');
    const isBold = styleLower.includes('bold') || styleLower.includes('brutalist') || styleLower.includes('neon');
    const isElegant = styleLower.includes('elegant') || styleLower.includes('luxury') || styleLower.includes('editorial');
    
    const padding = bp.containerPadding || (isGlass ? 'p-8' : 'p-10');
    const headlineFont = bp.fontFamily || (isBold ? 'Montserrat' : isElegant ? 'Playfair Display' : 'Plus Jakarta Sans');
    const subtitleFont = bp.subtitleFontFamily || 'Plus Jakarta Sans';
    const headlineFallback = getFontFallback(headlineFont);
    const subtitleFallback = getFontFallback(subtitleFont);
    
    const isLeftBleed = templateStyle === 'editorial_left_bleed' || templateStyle.includes('left_bleed') || templateStyle.includes('gradient');
    const finalTextColor = isLeftBleed 
      ? '#0F172A' // Always dark slate on white left-bleed panels
      : (bp.headlineColorOverride || bp.textColorOverride || colors.headlineColor);
    const finalSubtitleColor = isLeftBleed 
      ? '#1E293B' // Always dark charcoal on white left-bleed panels
      : (bp.subtitleColorOverride || bp.textColorOverride || colors.subtitleColor);
    const accentColor = finalTextColor || brandAccentColor || colors.headlineColor;
    const fontMultiplier = bp.fontSizeScale || 1.0;

    const featureList = resolveFeatureList(subtitle, headline, bp.features);
    
    let containerStyle = '';
    let containerClass = '';
    let headlineFontClass = '';
    let bodyFontClass = '';
    let buttonStyle = '';
    
    let weightClass = 'font-extrabold';
    if (bp.headlineWeight === 'black') weightClass = 'font-black';
    else if (bp.headlineWeight === 'semibold') weightClass = 'font-semibold';
    else if (bp.headlineWeight === 'medium') weightClass = 'font-medium';
    else if (bp.headlineWeight === 'bold') weightClass = 'font-bold';

    const finalBgColor = bp.backgroundColorOverride || (templateStyle === 'bold'
      ? (colors.isDarkBg ? 'rgba(15,23,42,0.35)' : 'rgba(255,255,255,0.35)')
      : templateStyle === 'elegant'
      ? (colors.isDarkBg ? 'rgba(9,15,30,0.3)' : 'rgba(255,250,245,0.3)')
      : `rgba(${colors.isDarkBg ? '15,23,42' : '255,255,255'}, ${colors.bgOpacityOverride || 0.25})`);

    const finalAccentColor = bp.accentColorOverride || brandAccentColor || brandBaseColor || '#8B5CF6';
    const finalBrandColor = brandBaseColor || '#0F172A';

    // Resolve premium, high-contrast, legibility-guaranteed CTA button colors
    let btnBg = finalAccentColor;
    let btnText = '#FFFFFF';
    
    if (colors.isDarkBg && !isLeftBleed) {
      // Dark background: white button with dark text is extremely legible and premium
      btnBg = '#FFFFFF';
      btnText = finalBrandColor && finalBrandColor !== 'transparent' ? finalBrandColor : '#0F172A';
    } else {
      // Light background: use solid brand color or rich dark slate if brand color is too light or missing
      btnBg = finalAccentColor && finalAccentColor !== 'transparent' && finalAccentColor !== '#FFFFFF' && finalAccentColor !== '#ffffff' ? finalAccentColor : '#0F172A';
      btnText = '#FFFFFF';
    }

    // Apply explicit LLM CTA button color choices if provided
    if (bp.ctaBackgroundColorOverride) {
      btnBg = bp.ctaBackgroundColorOverride;
    }
    if (bp.ctaTextColorOverride) {
      btnText = bp.ctaTextColorOverride;
    }

    // Apply template themes
    if (templateStyle === 'editorial_left_bleed' || templateStyle.includes('left_bleed') || templateStyle.includes('gradient')) {
      containerClass = `h-full max-w-[540px] p-16 flex flex-col justify-between transition-all duration-300`;
      containerStyle = `background: linear-gradient(to right, rgba(255, 255, 255, 0.98) 0%, rgba(255, 255, 255, 0.95) 45%, rgba(255, 255, 255, 0.8) 60%, rgba(255, 255, 255, 0) 100%); border: none !important; box-shadow: none !important;`;
      headlineFontClass = 'font-serif font-bold leading-tight';
      bodyFontClass = 'text-base font-normal leading-relaxed';
      buttonStyle = `background-color: ${btnBg}; color: ${btnText}; border-radius: 9999px; font-weight: 800;`;
    } else if (templateStyle === 'bold') {
      containerClass = `${padding} rounded-xl flex flex-col gap-5 shadow-2xl border-t-8 transition-all duration-300`;
      containerStyle = `background-color: ${finalBgColor}; border-color: ${btnBg};`;
      headlineFontClass = `${weightClass} tracking-tighter uppercase`;
      bodyFontClass = 'text-xs font-bold uppercase tracking-wider';
      buttonStyle = `background-color: ${btnBg}; color: ${btnText}; font-weight: 900; border-radius: 0.375rem;`;
    } else if (templateStyle === 'elegant') {
      containerClass = `glass-backplate max-w-[520px] ${padding} rounded-3xl flex flex-col gap-6 shadow-2xl border-2 transition-all duration-300`;
      containerStyle = `background-color: ${finalBgColor}; border-color: rgba(${colors.isDarkBg ? '255,255,255' : '15,23,42'}, 0.12);`;
      headlineFontClass = 'font-serif italic font-semibold leading-snug';
      bodyFontClass = 'text-sm font-light italic leading-relaxed';
      buttonStyle = `background-color: ${btnBg}; color: ${btnText}; border-radius: 9999px; border: 1px solid rgba(0,0,0,0.05); font-weight: 700;`;
    } else {
      containerClass = `glass-backplate max-w-[520px] ${padding} rounded-3xl flex flex-col gap-5 shadow-2xl transition-all duration-300`;
      containerStyle = `background-color: ${finalBgColor};`;
      headlineFontClass = `${weightClass} leading-tight tracking-tight`;
      bodyFontClass = 'text-sm font-medium leading-relaxed';
      buttonStyle = `background-color: ${btnBg}; color: ${btnText}; border-radius: 0.75rem; font-weight: 700;`;
    }

    if (layoutType === 'editorial_column' && templateStyle !== 'editorial_left_bleed' && !templateStyle.includes('left_bleed')) {
      containerClass = `h-full max-w-[500px] ${padding} flex flex-col gap-8 shadow-2xl transition-all duration-300`;
      containerStyle = `background-color: ${finalBgColor}; border-color: rgba(${colors.isDarkBg ? '255,255,255' : '15,23,42'}, 0.12); backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px);`;
    }

    if (bp.requireGlassmorphism === false && templateStyle !== 'editorial_left_bleed' && !templateStyle.includes('left_bleed')) {
      if (layoutType === 'editorial_column') {
        containerClass = `h-full max-w-[520px] ${padding} flex flex-col gap-8 transition-all duration-300 bg-transparent border-0 shadow-none backdrop-blur-none`;
      } else {
        containerClass = `max-w-[520px] ${padding} flex flex-col gap-5 transition-all duration-300 bg-transparent border-0 shadow-none backdrop-blur-none`;
      }
      containerStyle = `background: transparent; border: none; backdrop-filter: none; box-shadow: none;`;
    }

    
    // Sanitize dynamicHtmlBlock to prevent nested single/double quotes around font names from breaking the HTML attribute boundary
    if (bp.dynamicHtmlBlock) {
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /font-family:\s*['"\\/]*([^'";\\/]+)['"\\/]*/gi,
        "font-family: $1"
      );
      logger.info('Sanitized font-family single/double quotes. Preserved all custom LLM color layouts, opacities, and styling gradients.');

      // Fallback: Replace data-doodle placeholders with inline SVGs in case the LLM outputs placeholders instead of raw SVGs
      const { DOODLES } = require('./svgDoodles');
      // Match both <div data-doodle> and <span data-doodle> with any attribute order
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<(div|span)\s+[^>]*data-doodle=['"]([^'"]+)['"][^>]*data-doodle-color=['"]([^'"]+)['"][^>]*><\/(div|span)>/gi,
        (match, tag, doodleName, color) => {
          const doodleFn = (DOODLES as any)[doodleName];
          return doodleFn ? `<span style="display:inline-block;">${doodleFn(color)}</span>` : '';
        }
      );
      // Also handle reversed attribute order: data-doodle-color before data-doodle
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<(div|span)\s+[^>]*data-doodle-color=['"]([^'"]+)['"][^>]*data-doodle=['"]([^'"]+)['"][^>]*><\/(div|span)>/gi,
        (match, tag, color, doodleName) => {
          const doodleFn = (DOODLES as any)[doodleName];
          return doodleFn ? `<span style="display:inline-block;">${doodleFn(color)}</span>` : '';
        }
      );
      // Also handle self-closing variants: <span data-doodle="..." data-doodle-color="..." />
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<(div|span)\s+[^>]*data-doodle=['"]([^'"]+)['"][^>]*data-doodle-color=['"]([^'"]+)['"][^>]*\/>/gi,
        (match, tag, doodleName, color) => {
          const doodleFn = (DOODLES as any)[doodleName];
          return doodleFn ? `<span style="display:inline-block;">${doodleFn(color)}</span>` : '';
        }
      );
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<(div|span)\s+[^>]*data-doodle-color=['"]([^'"]+)['"][^>]*data-doodle=['"]([^'"]+)['"][^>]*\/>/gi,
        (match, tag, color, doodleName) => {
          const doodleFn = (DOODLES as any)[doodleName];
          return doodleFn ? `<span style="display:inline-block;">${doodleFn(color)}</span>` : '';
        }
      );

      // Normalize free-form LLM layouts so non-editorial blocks don't stretch
      // across the entire canvas and pin content to the extreme top and bottom.
      if (layoutType !== 'editorial_column') {
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(/\bh-full\b/g, '');
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
          /height:\s*100%\s*;?/gi,
          'height: auto; min-height: 520px;'
        );
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
          /justify-content:\s*space-between\s*;?/i,
          'justify-content: flex-start; gap: 28px;'
        );
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
          /max-width:\s*(580|600|640|680|720)px\s*;?/i,
          'max-width: 520px;'
        );
        logger.info('Normalized dynamicHtmlBlock placement for non-editorial layout.');
      }
    }

    // Post-process: Strip glassmorphism styles from dynamicHtmlBlock when requireGlassmorphism is false
    // This is a safety net in case the LLM still bakes glass styles into its HTML despite being told not to
    if (bp.dynamicHtmlBlock && bp.requireGlassmorphism === false) {
      // Remove backdrop-filter and -webkit-backdrop-filter inline styles
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /backdrop-filter:\s*blur\([^)]*\)\s*;?/gi, ''
      );
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /-webkit-backdrop-filter:\s*blur\([^)]*\)\s*;?/gi, ''
      );
      // Remove glass-backplate class references
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(/glass-backplate/g, '');
      // Remove backdrop-blur Tailwind classes
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(/backdrop-blur-\w+/g, '');
      logger.info('Stripped glassmorphism styles from dynamicHtmlBlock (requireGlassmorphism=false)');
    }

    const zIndexClass = bp.typographyZIndex === 'behind' ? 'z-10' : 'z-30';
    
    // Dynamic URL Font loaders
    const fontsToLoad = new Set<string>();
    if (headlineFont) fontsToLoad.add(headlineFont);
    if (subtitleFont) fontsToLoad.add(subtitleFont);

    // Extract any Google Fonts referenced in dynamicHtmlBlock inline styles
    // so they are loaded before Playwright renders the page
    if (bp.dynamicHtmlBlock) {
      const fontMatches = bp.dynamicHtmlBlock.matchAll(/font-family:\s*([^;}"']+)/gi);
      for (const match of fontMatches) {
        const families = match[1].split(',').map((f: string) => f.trim().replace(/['"]/g, ''));
        for (const family of families) {
          const normalized = family.trim();
          if (normalized && !['serif', 'sans-serif', 'cursive', 'monospace', 'inherit', 'initial', 'unset'].includes(normalized.toLowerCase())) {
            fontsToLoad.add(normalized);
          }
        }
      }
    }

    // Append premium cursive fonts Caveat and Pacifico
    fontsToLoad.add('Caveat');
    fontsToLoad.add('Pacifico');
    const fontParams = Array.from(fontsToLoad).map(f => formatGoogleFontParam(f));
    const unifiedFontsUrl = `https://fonts.googleapis.com/css2?${fontParams.join('&')}&display=swap`;

    // Map target quadrant to Tailwind CSS alignments
    let verticalAlign = 'items-start';
    let horizontalAlign = 'justify-start';

    const quad = finalQuadrant.toLowerCase();
    if (quad === 'center') {
      verticalAlign = 'items-center';
      horizontalAlign = 'justify-center';
    } else if (quad === 'top_center') {
      verticalAlign = 'items-start';
      horizontalAlign = 'justify-center';
    } else if (quad === 'bottom_center') {
      verticalAlign = 'items-end';
      horizontalAlign = 'justify-center';
    } else {
      if (quad.includes('bottom')) {
        verticalAlign = 'items-end';
      }
      if (quad.includes('right')) {
        horizontalAlign = 'justify-end';
      }
    }

    // Z-Index Panning and Parallax for Carousel
    let bgTransform = 'transform: scale(1.0);';
    let maskTransform = 'transform: scale(1.0);';
    
    if (slideIndex !== undefined) {
      // 4-slide carousel continuous panorama and parallax panning
      const scales = [1.25, 1.25, 1.25, 1.25];
      const bgPans = [10, 3.3, -3.3, -10]; // Background pans from left to right
      const maskPans = [5, 1.6, -1.6, -5];  // Foreground subject pans slower for parallax depth
      
      const bgPan = bgPans[slideIndex] || 0;
      const maskPan = maskPans[slideIndex] || 0;
      const bgScale = scales[slideIndex] || 1.25;
      const maskScale = slideIndex === 3 ? 1.05 : 1.15; // Slightly zoom out CTA slide to focus button
      
      bgTransform = `transform: scale(${bgScale}) translate(${bgPan}%, 0);`;
      maskTransform = `transform: scale(${maskScale}) translate(${maskPan}%, 2%);`; // slight vertical offset
    }

    // Convert raw background buffer to inline Base64 data URI
    const baseImageBase64 = baseImageBuffer.toString('base64');

    // Validate dynamicHtmlBlock: must contain at least one root <div to be usable.
    // If malformed or empty, clear it so the template system acts as fallback.
    if (bp.dynamicHtmlBlock) {
      const trimmed = bp.dynamicHtmlBlock.trim();
      const isValid = trimmed.length > 50 && trimmed.includes('<div');
      if (!isValid) {
        logger.warn('[htmlRenderer] dynamicHtmlBlock failed validation (missing root <div or too short) — falling back to template system.');
        bp.dynamicHtmlBlock = undefined;
      } else {
        // Strip data-render-features and data-render-statistics placeholders — the LLM
        // renders features inline in the numbered list, so injecting them again causes duplication.
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock
          .replace(/<span[^>]*data-render-features[^>]*>.*?<\/span>/gi, '')
          .replace(/<span[^>]*data-render-statistics[^>]*>.*?<\/span>/gi, '');
        // Prevent CTA buttons from overflowing the panel — strip nowrap and inject width cap
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock
          .replace(/white-space:\s*nowrap\s*[;!]*/gi, 'white-space: normal;')
          .replace(/(<button[^>]*style=")([^"]*)(max-width:[^;"]*;?\s*)/gi, '$1$2')
          .replace(/(<button[^>]*style=")/gi, '$1max-width:100%;word-break:break-word;');
        logger.info(`[htmlRenderer] dynamicHtmlBlock validated (${trimmed.length} chars) — using LLM-generated HTML.`);
      }
    }
    
    const resolvedLogo = brandLogoUrl || 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&auto=format&fit=crop&q=60';
    const resolvedBrandName = brandName || 'Aladdyn Social';



    // Editorial full-height side columns template
    if (layoutType === 'editorial_column') {
      verticalAlign = 'items-stretch';
      horizontalAlign = quad.includes('right') ? 'justify-end' : 'justify-start';
      
      const isLeftBleed = templateStyle === 'editorial_left_bleed' || templateStyle.includes('left_bleed') || templateStyle.includes('gradient');
      if (isLeftBleed) {
        containerClass = `h-full max-w-[540px] p-16 flex flex-col justify-between transition-all duration-300 ${quad.includes('right') ? 'border-l' : 'border-r'}`;
        containerStyle = `background: linear-gradient(to right, rgba(255, 255, 255, 0.98) 0%, rgba(255, 255, 255, 0.95) 45%, rgba(255, 255, 255, 0.8) 60%, rgba(255, 255, 255, 0) 100%); border: none !important; box-shadow: none !important;`;
      } else {
        containerClass = `h-full max-w-[500px] ${padding} flex flex-col gap-8 shadow-2xl transition-all duration-300 ${quad.includes('right') ? 'border-l' : 'border-r'}`;
        containerStyle = `background-color: ${finalBgColor}; border-color: rgba(${colors.isDarkBg ? '255,255,255' : '15,23,42'}, 0.12); backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px);`;
      }
    }

    const headlineLen = (headline || '').length;
    let baseRem = 2.1; // default ~33px
    if (headlineLen <= 12) {
      baseRem = 2.6; // ~41px
    } else if (headlineLen > 24) {
      baseRem = 1.7; // ~27px
    }
    let headlineSizeStyle = `font-size: ${baseRem * fontMultiplier}rem; line-height: 1.15; font-family: '${headlineFont}', ${headlineFallback}; word-break: keep-all; overflow-wrap: normal; hyphens: none;`;
    let subtitleSizeStyle = `font-size: ${0.95 * fontMultiplier}rem; line-height: 1.5; font-family: '${subtitleFont}', ${subtitleFallback}; word-break: keep-all; overflow-wrap: normal; hyphens: none;`;

    // Strip out all frosted glass backgrounds, borders, shadows, and card blurs if glassmorphism is disabled
    if (bp.requireGlassmorphism === false) {
      if (layoutType === 'editorial_column') {
        containerClass = `h-full max-w-[520px] ${padding} flex flex-col gap-8 transition-all duration-300 bg-transparent border-0 shadow-none backdrop-blur-none`;
      } else {
        containerClass = `max-w-[520px] ${padding} flex flex-col gap-5 transition-all duration-300 bg-transparent border-0 shadow-none backdrop-blur-none`;
      }
      containerStyle = `background: transparent; border: none; backdrop-filter: none; box-shadow: none;`;

      // Compute directional text shadows that match the scene's lighting
      const lightH = colors.lightDirection?.horizontal || -0.1;
      const lightV = colors.lightDirection?.vertical || -0.1;

      // Shadow offset opposes the light source (shadow falls away from light)
      const shadowOffsetX = Math.round(-lightH * 6); // -6px to +6px
      const shadowOffsetY = Math.round(-lightV * 6) + 2; // baseline 2px down

      // Soft diffuse text shadows for elegant contrast without harsh borders
      const shadowColor = colors.isDarkBg ? 'rgba(0,0,0,0.35)' : 'rgba(255,255,255,0.35)';
      const diffuseColor = colors.isDarkBg ? 'rgba(0,0,0,0.15)' : 'rgba(255,255,255,0.15)';

      const textShadowCss = `text-shadow: ${shadowOffsetX}px ${shadowOffsetY}px 8px ${shadowColor}, ${shadowOffsetX * 1.5}px ${shadowOffsetY * 1.5}px 24px ${diffuseColor};`;
      // Disabled text shadows to keep typography clean and crisp
    }

    // Solve checklists / comparison boxes
    let featureListHtml = '';
    let comparisonHtml = '';

    if (layoutType === 'feature_list' || layoutType === 'editorial_column') {
      let itemsLi = '';
      
      const featureElements = copyElements?.filter(e => e.type === 'feature' || e.type === 'badge') || [];
      const fallbackFeatures: any[] = featureElements.length > 0 
        ? featureElements 
        : featureList.map(feat => {
            const parsed = parseFeature(feat);
            return { text: parsed.text, icon: parsed.isEmoji ? parsed.icon : undefined, isNegative: parsed.isNegative, iconName: undefined };
          });
      
      fallbackFeatures.forEach(el => {
        const badgeContent = renderIconBadge({
          iconName: el.iconName,
          emoji: el.icon,
          isNegative: el.isNegative,
          accentColor: finalAccentColor,
          isDarkBg: colors.isDarkBg,
          size: 28,
          badgeStyle: bp.badgeStyle
        });

        const textShadowStyle = ''; // Disabled text shadows to keep typography clean and crisp

        itemsLi += `
          <li style="display: flex !important; flex-direction: row !important; align-items: center !important; justify-content: flex-start !important; gap: 12px !important; margin-bottom: 8px; width: 100% !important; text-align: left !important;" class="flex items-center gap-3 w-full text-left justify-start">
            ${badgeContent}
            <span style="color: ${finalSubtitleColor}; font-family: '${subtitleFont}', ${subtitleFallback}; ${textShadowStyle} font-size: 0.95rem; font-weight: 500;" class="ad-feature text-sm font-semibold">${el.text}</span>
          </li>
        `;
      });
      
      if (fallbackFeatures.length > 0) {
        featureListHtml = `<ul style="width: 100% !important; display: flex !important; flex-direction: column !important; align-items: flex-start !important; justify-content: flex-start !important; text-align: left !important; gap: 10px;" class="flex flex-col gap-2.5 mt-4 w-full">${itemsLi}</ul>`;
      }
    } else if (layoutType === 'split_screen') {
      const featureElements = copyElements?.filter(e => e.type === 'feature' || e.type === 'badge') || [];
      const fallbackFeatures: any[] = featureElements.length > 0 
        ? featureElements 
        : featureList.map(feat => {
            const parsed = parseFeature(feat);
            return { text: parsed.text, icon: parsed.isEmoji ? parsed.icon : undefined, isNegative: parsed.isNegative, iconName: undefined };
          });

      const usFeatures = fallbackFeatures.filter((_, i) => i % 2 === 0);
      const themFeatures = fallbackFeatures.filter((_, i) => i % 2 !== 0);
      
      if (fallbackFeatures.length > 0) {
        comparisonHtml = `
          <div class="grid grid-cols-2 gap-4 w-full mt-4 z-10">
            <!-- Left box: Us -->
            <div class="bg-emerald-950/40 border border-emerald-500/20 backdrop-blur-md rounded-2xl p-4 flex flex-col gap-3">
              <div class="text-[10px] font-black uppercase text-emerald-400 tracking-widest border-b border-emerald-500/20 pb-1.5">OUR WAY</div>
              <ul class="flex flex-col gap-2.5">
                ${usFeatures.map(item => {
                  const badge = renderIconBadge({
                    iconName: item.iconName,
                    emoji: item.icon,
                    isNegative: false,
                    accentColor: '#10B981', // emerald-500
                    isDarkBg: true,
                    size: 20,
                    badgeStyle: bp.badgeStyle
                  });
                  return `
                    <li class="flex items-center gap-2 text-xs font-bold text-white uppercase leading-snug">
                      ${badge}
                      <span>${item.text}</span>
                    </li>
                  `;
                }).join('')}
              </ul>
            </div>
            
            <!-- Right box: Them -->
            <div class="bg-rose-950/40 border border-rose-500/20 backdrop-blur-md rounded-2xl p-4 flex flex-col gap-3">
              <div class="text-[10px] font-black uppercase text-rose-400 tracking-widest border-b border-rose-500/20 pb-1.5">THEM / OTHERS</div>
              <ul class="flex flex-col gap-2.5">
                ${themFeatures.map(item => {
                  const badge = renderIconBadge({
                    iconName: item.iconName,
                    emoji: item.icon,
                    isNegative: true,
                    accentColor: '#F43F5E', // rose-500
                    isDarkBg: true,
                    size: 20,
                    badgeStyle: bp.badgeStyle
                  });
                  return `
                    <li class="flex items-center gap-2 text-xs font-bold text-slate-300 uppercase leading-snug">
                      ${badge}
                      <span>${item.text}</span>
                    </li>
                  `;
                }).join('')}
              </ul>
            </div>
          </div>
        `;
      }
    }

    // Testimonial block is NO LONGER hardcoded.
    // The LLM Layout Director will generate a dynamicHtmlBlock with review content
    // ONLY when the post's content intent is genuinely a customer review/testimonial.
    // This prevents every post from getting a ★★★★★ editorial review overlay.
    const testimonialHtml = '';

    // Watermark display word removed — it degraded visual quality by placing
    // ugly text behind the product subject without serving any design purpose.

    // Render statistics blocks from CopyBlueprint elements
    let statisticsHtml = '';
    if (copyElements && copyElements.length > 0) {
      const statElements = copyElements.filter(el => el.type === 'statistic' && el.value);
      if (statElements.length > 0) {
        statisticsHtml = renderStatisticsBlock({
          stats: statElements.map(el => ({
            value: el.value!,
            text: el.text,
            iconName: el.iconName
          })),
          accentColor: finalAccentColor,
          headlineColor: finalTextColor,
          subtitleColor: finalSubtitleColor,
          headlineFont: headlineFont,
          subtitleFont: subtitleFont,
          isDarkBg: colors.isDarkBg
        });
      }
    }

    if (bp.dynamicHtmlBlock) {
      const hasFeaturePlaceholder = /data-render-features=['"]true['"]/i.test(bp.dynamicHtmlBlock);
      const hasStatisticPlaceholder = /data-render-statistics=['"]true['"]/i.test(bp.dynamicHtmlBlock);

      // Replace explicit placeholders if the LLM used them
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<div[^>]*data-render-features=['"]true['"][^>]*><\/div>/gi,
        featureListHtml || ''
      );
      bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
        /<div[^>]*data-render-statistics=['"]true['"][^>]*><\/div>/gi,
        statisticsHtml || ''
      );

      // Detect whether the LLM already wrote inline feature content (numbered list, ad-feature items, etc.)
      // If it did, skip the fallback injection to prevent duplication.
      const hasInlineFeatures = /ad-feature|ad-body|<li|<ol|numbered|step/i.test(bp.dynamicHtmlBlock);

      // Only inject renderer-owned feature list if the LLM wrote NO features at all
      if (!hasFeaturePlaceholder && !hasInlineFeatures && featureListHtml) {
        const buttonMatch = bp.dynamicHtmlBlock.match(/<button[\s\S]*?<\/button>/i);
        if (buttonMatch) {
          bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(
            /<button[\s\S]*?<\/button>/i,
            `${featureListHtml}$&`
          );
        } else {
          bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(/<\/div>\s*$/, `${featureListHtml}</div>`);
        }
        logger.info('Injected renderer-owned SVG feature list into dynamicHtmlBlock (LLM had no inline features).');
      } else if (!hasFeaturePlaceholder && hasInlineFeatures) {
        logger.info('Skipping renderer feature injection — LLM already wrote inline feature content.');
      }

      // Only inject statistics if no placeholder and no inline stat content
      const hasInlineStats = /statistic|stat-block|data-value|\d+%/i.test(bp.dynamicHtmlBlock);
      if (!hasStatisticPlaceholder && !hasInlineStats && statisticsHtml) {
        bp.dynamicHtmlBlock = bp.dynamicHtmlBlock.replace(/<\/div>\s*$/, `${statisticsHtml}</div>`);
      }
    }

    // 3. Compile Z-index sandwich HTML template
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <!-- Blocking high-performance stylesheet loader for custom Google Fonts -->
        <link rel="stylesheet" href="${unifiedFontsUrl}">
        <style>
          body {
            -webkit-font-smoothing: antialiased;
          }
          .glass-backplate {
            backdrop-filter: blur(24px);
            -webkit-backdrop-filter: blur(24px);
            border: 1px solid rgba(${colors.isDarkBg ? '255,255,255' : '0,0,0'}, 0.08);
          }
          svg.lucide {
            display: inline-block !important;
            vertical-align: middle !important;
            margin-right: 6px;
            margin-bottom: 2px;
          }
          .font-script {
            font-family: 'Caveat', 'Pacifico', cursive !important;
            font-size: 1.25em !important;
            line-height: 1.0 !important;
            display: inline-block !important;
            transform: rotate(-1.5deg);
          }
          .text-accent-color {
            color: ${finalAccentColor} !important;
          }
          .font-headline-bold {
            text-transform: uppercase !important;
            font-weight: 900 !important;
            letter-spacing: -0.01em !important;
          }

          /* ===== ELEGANT TYPOGRAPHIC SIZING (PREMIUM UPDATE) ===== */
          /* Sensible defaults — inline styles from dynamicHtmlBlock will override these */
          .ad-headline {
            font-size: 42px;
            line-height: 1.15 !important;
            font-weight: 800 !important;
            letter-spacing: -0.015em !important;
            word-break: keep-all !important;
            overflow-wrap: normal !important;
            hyphens: none !important;
          }
          .ad-subtitle {
            font-size: 18px;
            line-height: 1.55 !important;
            font-weight: 400 !important;
            letter-spacing: -0.005em !important;
            word-break: keep-all !important;
            overflow-wrap: normal !important;
            hyphens: none !important;
          }
          .ad-body, .ad-feature {
            font-size: 15px;
            line-height: 1.5 !important;
            font-weight: 500 !important;
            word-break: keep-all !important;
            overflow-wrap: normal !important;
            hyphens: none !important;
          }
          .ad-badge {
            font-size: 11px;
            letter-spacing: 0.18em !important;
            text-transform: uppercase !important;
            font-weight: 600 !important;
            opacity: 0.9 !important;
            word-break: keep-all !important;
            overflow-wrap: normal !important;
            hyphens: none !important;
          }
          .ad-cta {
            font-size: 13px;
            font-weight: 700 !important;
            padding: 10px 24px !important;
            text-transform: uppercase !important;
            letter-spacing: 0.08em !important;
            border-radius: 6px !important;
            white-space: normal !important;
            word-break: break-word !important;
            max-width: 100% !important;
            flex-shrink: 1 !important;
            align-self: flex-start !important;
          }

          /* ===== BRAND COLOR UTILITIES ===== */
          :root {
            --brand-color: ${finalBrandColor};
            --accent-color: ${finalAccentColor};
          }
          .text-brand-color  { color: var(--brand-color) !important; }
          .text-brand-accent { color: var(--accent-color) !important; }
          .bg-brand-glass {
            background: rgba(var(--brand-color-rgb, 99, 102, 241), 0.12) !important;
            backdrop-filter: blur(8px) !important;
            border: 1px solid rgba(var(--brand-color-rgb, 99, 102, 241), 0.25) !important;
          }
          .divider-accent {
            display: block !important;
            width: 48px !important;
            height: 3px !important;
            background: var(--accent-color) !important;
            border-radius: 2px !important;
            margin: 12px 0 !important;
          }
          /* Flex/grid helpers for multi-column layouts */
          .ad-row    { display: flex !important; flex-direction: row !important; align-items: center !important; gap: 12px !important; }
          .ad-col    { display: flex !important; flex-direction: column !important; gap: 8px !important; }
          .ad-grid-2 { display: grid !important; grid-template-columns: 1fr 1fr !important; gap: 16px !important; }

          /* ===== PREMIUM SCATTERED SCRIM & CONTRAST SHIELDS ===== */
          /* High-end soft diffuse shadows that create absolute readability without harsh contours */
          .text-contrast-shield {
            text-shadow:
              0px 4px 18px rgba(0,0,0,0.65),
              0px 2px 8px rgba(0,0,0,0.45),
              0px 0px 30px rgba(0,0,0,0.35) !important;
          }
          /* For dark text on light backgrounds */
          .text-contrast-shield-light {
            text-shadow:
              0px 4px 18px rgba(255,255,255,0.75),
              0px 2px 8px rgba(255,255,255,0.55),
              0px 0px 30px rgba(255,255,255,0.45) !important;
          }
        </style>
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://unpkg.com/lucide@0.460.0/dist/umd/lucide.js"></script>
      </head>
      <body class="m-0 p-0 relative overflow-hidden" style="width: ${width}px; height: ${height}px; background-color: #121212;">
        
        <!-- Z-Index 0: Background AI Scene (Base Image) -->
        <img src="data:image/png;base64,${baseImageBase64}" class="w-full h-full object-cover absolute top-0 left-0 z-0" style="${bgTransform}" />

        <!-- Z-Index 10/30: Composite Overlay Grid Container (Typography Card) -->
        <div class="w-full h-full absolute top-0 left-0 ${zIndexClass}" style="overflow:hidden; ${bp.dynamicHtmlBlock ? '' : `${layoutType === 'editorial_column' ? '' : 'padding: 56px;'} display:flex; align-items:${verticalAlign.replace('items-','') || 'flex-start'}; justify-content:${horizontalAlign.replace('justify-','') || 'flex-start'};`}">
                    ${bp.dynamicHtmlBlock ? bp.dynamicHtmlBlock : `
          <!-- Dynamic Design Backplate -->
          <div class="${containerClass}" style="${containerStyle}">
            <!-- Ad Headline -->
            <h1 class="ad-headline ${headlineFontClass}" style="color: ${finalTextColor}; ${headlineSizeStyle}">
              ${headline}
            </h1>

            <!-- Ad Subtitle description (Hidden in comparison layout to save space) -->
            ${layoutType === 'split_screen' ? '' : `
              <p class="ad-subtitle ${bodyFontClass}" style="color: ${finalSubtitleColor}; opacity: 0.95; ${subtitleSizeStyle}">
                ${subtitle}
              </p>
            `}

            <!-- Checklist features -->
            ${featureListHtml}

            <!-- Us vs Them comparison boxes -->
            ${comparisonHtml}

            <!-- Statistics Metrics Grid -->
            ${statisticsHtml}

            <!-- Testimonial / Review Block -->
            ${testimonialHtml}

            <!-- CTA Callout Button -->
            <button class="ad-cta mt-2 py-3.5 px-7 text-xs font-bold self-start shadow-lg uppercase tracking-wider transition-all hover:scale-105 active:scale-95 flex-shrink-0"
                    style="${buttonStyle}; ${bp.ctaIconStyle === 'circular_arrow' ? 'border-radius: 9999px !important; padding-left: 12px !important;' : ''}; font-family: '${subtitleFont}', ${subtitleFallback}; display: flex; align-items: center; justify-content: center; gap: 8px; white-space: nowrap !important;">
              ${bp.ctaIconStyle === 'circular_arrow' 
                ? `<span style="display: inline-flex !important; align-items: center !important; justify-content: center !important; width: 28px !important; height: 28px !important; border-radius: 50% !important; background-color: #ffffff !important; color: ${btnBg} !important; margin-right: 4px !important; flex-shrink: 0 !important;">
                     <i data-lucide="arrow-right" style="width: 14px !important; height: 14px !important; color: ${btnBg} !important; stroke-width: 2.5 !important;"></i>
                   </span>` 
                : ''
              }
              <span>${cta}</span>
              ${bp.ctaIconStyle === 'inline'
                ? `<i data-lucide="arrow-right" style="width: 14px !important; height: 14px !important; stroke-width: 2.5 !important;"></i>`
                : ''
              }
            </button>
          </div>
          `}
        </div>

        <!-- Z-Index 40: Bottom Footer Trust Bar -->
        <div style="position: absolute; bottom: 0; left: 0; width: 100%; z-index: 40; pointer-events: none;
                    background: linear-gradient(to right, ${finalBrandColor}ee, ${finalAccentColor}cc);
                    display: flex; align-items: center; justify-content: space-between;
                    padding: 14px 32px; gap: 16px;">
          <!-- Trust badges: prefer CopyBlueprint badge elements, then bp.features, then generic fallback -->
          <div style="display: flex; align-items: center; gap: 20px; flex: 1;">
            ${(() => {
              // 1. Use badge-type elements from copyElements if available
              const badgeElements = (copyElements || []).filter((el: any) => el.type === 'badge').map((el: any) => el.text);
              // 2. Fall back to bp.features
              const featureBadges = bp.features && bp.features.length > 0 ? bp.features.slice(0, 3) : [];
              // 3. Pad with short feature text (first 3 words) if still under 3 badges
              const featureShorts = (copyElements || [])
                .filter((el: any) => el.type === 'feature')
                .map((el: any) => el.text.split(/\s+/).slice(0, 3).join(' '))
                .slice(0, 3);
              // 4. Generic fallback
              let badges = badgeElements.length > 0 ? badgeElements :
                           featureBadges.length > 0 ? featureBadges : featureShorts;
              // Ensure exactly 3 badges
              while (badges.length < 3) badges.push(['Quality Assured', 'Made with Care', 'Trusted Brand'][badges.length]);
              badges = badges.slice(0, 3);
              return badges.map((badge: string) => `
                <div style="display: flex; align-items: center; gap: 6px;">
                  <i data-lucide="check-circle" style="width: 14px; height: 14px; color: rgba(255,255,255,0.9); flex-shrink: 0;"></i>
                  <span style="font-size: 11px; font-weight: 600; color: rgba(255,255,255,0.92); letter-spacing: 0.06em; text-transform: uppercase; font-family: 'Plus Jakarta Sans', sans-serif; white-space: nowrap;">${badge}</span>
                </div>
              `).join('');
            })()}
          </div>
          <!-- CTA pill -->
          <div style="background: rgba(255,255,255,0.95); border-radius: 8px; padding: 8px 18px; display: flex; align-items: center; gap: 8px; flex-shrink: 0;">
            <i data-lucide="phone" style="width: 13px; height: 13px; color: ${finalBrandColor};"></i>
            <span style="font-size: 11px; font-weight: 800; color: ${finalBrandColor}; letter-spacing: 0.08em; text-transform: uppercase; font-family: 'Plus Jakarta Sans', sans-serif; white-space: nowrap;">${cta}</span>
          </div>
        </div>

        <!-- Z-Index 20: Foreground transparent subject mask overlay (depth sandwiching with realistic cast shadow) -->
        ${subjectMaskUrl ? `
          <img src="${subjectMaskUrl}" 
               class="w-full h-full object-cover absolute top-0 left-0 z-20 pointer-events-none" 
               style="filter: drop-shadow(0 15px 30px rgba(0,0,0,0.35)) drop-shadow(0 5px 15px rgba(0,0,0,0.22)); ${maskTransform}" />
        ` : ''}

        <script>lucide.createIcons();</script>
      </body>
      </html>
    `;

    // 4. Ingest and render HTML page contents
    await page.setContent(htmlContent, { timeout: 10000, waitUntil: 'domcontentloaded' });

    // Wait for Tailwind CDN to load and compile, with a hard timeout so we never hang.
    // If Tailwind fails to load (network issues), rendering will still proceed with inline styles.
    await Promise.race([
      page.waitForLoadState('load').catch(() => {}),
      page.evaluate(() => new Promise(resolve => setTimeout(resolve, 5000))),
    ]);

    // Ensure all Google Web Fonts are fully loaded before capturing screenshot
    try {
      await page.evaluate(() => (globalThis as any).document.fonts.ready);
      logger.info('Google Web Fonts fully loaded and active.');
    } catch (fontError: any) {
      logger.warn(`Failed waiting for fonts to load: ${fontError.message}`);
    }

    // Give the dynamic Tailwind CDN compiler script enough time to process classes and inject final styles
    await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 500)));

    // Wait for Lucide icons to initialize and render SVGs
    await page.evaluate(() => {
      const win = globalThis as any;
      if (typeof win.window !== 'undefined' && typeof win.window.lucide !== 'undefined') {
        win.window.lucide.createIcons();
      }
      return new Promise(resolve => setTimeout(resolve, 300));
    });

    // 5. Take full page viewport composite screenshot
    const finalAdBuffer = await page.screenshot({
      type: 'png',
      fullPage: true,
    });

    logger.info('✓ Successfully composited high-fidelity ad screenshot.');
    await browser.close();

    return finalAdBuffer;

  } catch (error: any) {
    logger.error(`Playwright ad composite rendering failed: ${error.message}`);
    await browser.close();
    throw error;
  }
}
