import { callLlm } from '../utils/llmClient';
import { createLogger } from '../utils/logger';
import { CopyBlueprint } from '../types/content';
import { DOODLES } from './svgDoodles';

const logger = createLogger({ service: 'layout-director' });

export interface LayoutBlueprint {
  designArchetype: string; // e.g. "glassmorphism", "brutalist minimal", "dark mode neon", etc.
  visual_reasoning: string; // NEW: The LLM must explicitly explain its chronological layout hierarchy (e.g. '1. Main Title placed in top_left. 2. CTA placed below title.') before writing HTML.
  layoutType: 'classic' | 'feature_list' | 'editorial_column' | 'split_screen' | 'liquid';
  requireGlassmorphism: boolean; // whether to add frosted glass card / card backplate, or let the text sit directly on the background
  fontFamily: string; // e.g. "Plus Jakarta Sans" or "Playfair Display" or "Bebas Neue"
  subtitleFontFamily?: string;
  headlineWeight: 'black' | 'bold' | 'semibold' | 'medium';
  fontSizeScale: number; // e.g. 0.85 to 1.15
  containerPadding: 'p-6' | 'p-8' | 'p-10' | 'p-12';
  backgroundColorOverride?: string; // e.g. 'rgba(15, 23, 42, 0.45)'
  textColorOverride?: string; // e.g. '#FFFFFF'
  headlineColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for the headline text
  subtitleColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for subtitles/descriptions
  accentColorOverride?: string; // Harmonious accent color chosen by the LLM for checklists, borders, icons, etc.
  ctaBackgroundColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for CTA background
  ctaTextColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for CTA button text
  badgeStyle?: 'translucent' | 'solid' | 'double_ring'; // Custom luxury visual style for features list checkmarks
  ctaIconStyle?: 'none' | 'inline' | 'circular_arrow'; // Allows the LLM to choose the premium circular arrow indicator
  useScriptHighlight?: boolean; // Instructs the compositor to load cursive scripts
  features?: string[]; // custom visual feature list items
  dynamicHtmlBlock?: string; // Full freeform HTML/CSS string generated by the LLM for website-quality ad rendering
  typographyZIndex?: 'behind' | 'in_front'; // NEW: programmatically and creatively solved Z-index stacking
  
  // Custom Dynamic Slide copy/label overrides for carousel slides
  slideHeader?: string;     // e.g. "Key", "Proven", "Experience"
  slideHighlight?: string;  // e.g. "Formulations", "Efficacy", "The Difference"
  slideSub?: string;        // e.g. "02 / 04 — BRAND POTENCY", "03 / 04 — PURE EFFICACY", "04 / 04 — READY TO GLOW"
  slideText?: string;       // e.g. "ACTIVES", "BENEFIT", "ADVANTAGE"
}


/**
 * Double-Pass Layout Director LLM Agent.
 * 
 * Performs creative layout engineering after base image generation to mathematically solve
 * Safe layout positioning, design archetype alignment, custom padding bounds, and contrast-safe coloring.
 */
export async function generateLayoutBlueprint(params: {
  imagePrompt: string;
  industry: string;
  services: string[];
  baseColor: string;
  accentColor?: string;
  geography?: string;
  safestQuadrant: string;
  quadrantScores?: Record<string, number>;
  contrastMetrics: {
    isDarkBg: boolean;
    headlineColor?: string;
    subtitleColor?: string;
    averageColorHex?: string;
    averageColorName?: string;
    detailedRegions?: {
      quadrantHeadline: any;
      quadrantSubtitle: any;
      quadrantFeatures: any;
      quadrantCta: any;
      columnHeadline: any;
      columnSubtitle: any;
      columnFeatures: any;
      columnCta: any;
    };
  };
  canvasDimensions?: { width: number; height: number };
  slideIndex?: number;
  feedback?: string;
  copyBlueprint: CopyBlueprint;
}): Promise<LayoutBlueprint> {
  logger.info(`Invoking second-pass LLM Layout Director to design ad layout (SlideIndex: ${params.slideIndex !== undefined ? params.slideIndex : 'N/A'})...`);

  // Intent classification is handled entirely by the LLM — no regex pre-classification.
  // Passing raw topic, caption, and pillar directly so the LLM can reason about intent freely.

  const headlineColor = params.contrastMetrics.headlineColor || '#FFFFFF';
  const subtitleColor = params.contrastMetrics.subtitleColor || '#E2E8F0';
  const avgColorHex = params.contrastMetrics.averageColorHex || '#121212';
  const avgColorName = params.contrastMetrics.averageColorName || 'Unknown Dark Backdrop';

  const accentColor = params.accentColor || params.baseColor || '#8B5CF6';
  const geography = params.geography || 'India';

  const slideContext = params.slideIndex !== undefined ? `
- You are designing **Slide ${params.slideIndex}** (out of a 4-slide carousel):
  * **Slide 0 (Cover)**: Captures attention, extremely bold and dramatic title. Let the background scene shine, placing the main headline beautifully in the ${params.safestQuadrant} quadrant.
  * **Slide 1 (Strengths / Core Advantages)**: Highlight 2-3 specific features, active ingredients, or core capabilities with beautiful row blocks, circular badges/icons, or checklist items.
  * **Slide 2 (Measurable Impact / Proven Efficacy)**: Showcase tangible outcomes, metrics, progress bars, or a comparison box (Us vs Them).
  * **Slide 3 (CTA / Action Card)**: High-converting closure with review star rating (★ ★ ★ ★ ★), a button, and clear closing copy.
` : `
- You are designing a standalone high-fidelity ad graphic post. Apply a premium custom layout that highlights the primary subject while rendering clean, highly readable overlays.
`;

  // Inject a subtle creative direction nudge to steer each generation toward
  // a slightly different aesthetic, while keeping things professional.
  const creativeDirections = [
    "brutalist minimal with strong geometric shapes",
    "editorial magazine spread with asymmetric layout",
    "luxury matte black with gold accents",
    "organic earth-tone with natural textures",
    "pastel dreamy with soft gradients",
    "bold neon with high contrast elements",
    "vintage retro with serif typography",
    "clean Scandinavian with lots of whitespace",
    "cyberpunk holographic with electric hues",
    "Y2K nostalgia with bubbly typography",
    "high-end cinematic with dramatic lighting",
    "surrealist floating elements with soft shadows",
    "monochrome photography with vibrant text accents",
    "glassmorphism UI with ultra-thin sleek lines",
    "elegant organic curves with soft lighting",
    "cinematic and highly polished"
  ];
  const creativeDirection = creativeDirections[Math.floor(Math.random() * creativeDirections.length)];

  // These are the CSS anchors provided to the LLM. 
  // We provide full-height columns or full-width rows so the Master Container can breathe.
  // NOTE: height is capped at calc(100% - 70px) to avoid overlapping the persistent footer bar.
  const allCoordinates: Record<string, string> = {
    top_left: 'style="position: absolute; top: 0; left: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-start;"',
    top_center: 'style="position: absolute; top: 0; left: 0; width: 100%; height: 45%; max-height: 540px; padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-start; align-items: center;"',
    top_right: 'style="position: absolute; top: 0; right: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-end;"',
    
    middle_left: 'style="position: absolute; top: 0; left: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: center; align-items: flex-start;"',
    middle_center: 'style="position: absolute; top: 0; left: 0; width: 100%; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: center; align-items: center;"',
    middle_right: 'style="position: absolute; top: 0; right: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: center; align-items: flex-end;"',
    
    bottom_left: 'style="position: absolute; top: 0; left: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-end; align-items: flex-start;"',
    bottom_center: 'style="position: absolute; bottom: 70px; left: 0; width: 100%; height: 45%; max-height: 540px; padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-end; align-items: center;"',
    bottom_right: 'style="position: absolute; top: 0; right: 0; width: 50%; max-width: 600px; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: flex-end; align-items: flex-end;"'
  };

  let allowedCoordinatesStr = '';
  if (params.quadrantScores) {
    const safeTiles = Object.entries(params.quadrantScores)
      .filter(([key, score]) => score < 0.35) // loosened threshold to find adjacent tiles
      .sort((a, b) => a[1] - b[1])
      .slice(0, 3); // MAX 3 TILES! Prevents scattering.
    
    // Always ensure the safestQuadrant is in the list
    if (!safeTiles.find(t => t[0] === params.safestQuadrant)) {
       safeTiles.unshift([params.safestQuadrant, 0]);
    }

    allowedCoordinatesStr = safeTiles.slice(0, 3).map(t => `     * ${t[0]}: ${allCoordinates[t[0]] || allCoordinates.top_left}`).join('\n');
  } else {
    allowedCoordinatesStr = `     * ${params.safestQuadrant}: ${allCoordinates[params.safestQuadrant] || allCoordinates.top_left}`;
  }

  let feedbackSection = '';
  if (params.feedback) {
    feedbackSection = `\nUSER LAYOUT FEEDBACK & DIRECTIONS (Follow these instructions to design the layout blueprint tokens appropriately):\n"${params.feedback}"\n`;
  }

  const detailedRegions = params.contrastMetrics.detailedRegions;
  let regionsInfoStr = '';
  if (detailedRegions) {
    regionsInfoStr = `
- SPECIFIC PIXEL COLORS BEHIND EACH TEXT COMPONENT SEPARATELY:
  Depending on your chosen layout structure (editorial column vs standard quadrant-based card/floating), the exact pixel background colors directly behind where each component will be placed are:
  * For Quadrant-based cards / floating layouts (standard classic, feature_list, split_screen):
    - Headline Region: ${detailedRegions.quadrantHeadline.averageColorName} (Hex: ${detailedRegions.quadrantHeadline.averageColorHex}, isDarkBg: ${detailedRegions.quadrantHeadline.isDarkBg})
    - Subtitle/Body Region: ${detailedRegions.quadrantSubtitle.averageColorName} (Hex: ${detailedRegions.quadrantSubtitle.averageColorHex}, isDarkBg: ${detailedRegions.quadrantSubtitle.isDarkBg})
  * For Quadrant-based cards:
    - Headline Region: ${detailedRegions.quadrantHeadline.averageColorName} (${detailedRegions.quadrantHeadline.averageColorHex})
    - Subtitle Region: ${detailedRegions.quadrantSubtitle.averageColorName} (${detailedRegions.quadrantSubtitle.averageColorHex})
  * For Column-based panels:
    - Headline Region: ${detailedRegions.columnHeadline.averageColorName} (${detailedRegions.columnHeadline.averageColorHex})
    - Subtitle Region: ${detailedRegions.columnSubtitle.averageColorName} (${detailedRegions.columnSubtitle.averageColorHex})
`;
  }

  const prompt = `You are a world-class Visual Design Director at a luxury ad agency. A highly sophisticated background image asset has been generated and pre-composed for a premium D2C brand or high-performance B2B enterprise campaign. 

YOUR SOLE MISSION IS TO ELEVATE THIS PREMIUM BACKGROUND ASSET INTO A STUNNING, MULTI-DIMENSIONAL AD MASTERPIECE by matching it to one of our 5 High-Fidelity Contextual Archetypes!

HOLISTIC VISUALIZATION (THINK LIKE A FINAL COMPOSITOR):
Do NOT just output random HTML text blocks blindly! Visualize the FINAL generated image. Imagine how elements physically overlay on a 1080px canvas. Every absolute position, margin, padding, and alignment must serve the final visual balance of the ad. Treat typography as structural art. Use breathing room, elegant high-fashion typography rules, purposeful asymmetry, and luxury spacing.

🎨 THE 5 HIGH-FIDELITY CONTEXTUAL ARCHETYPES:
You MUST classify the campaign into one of these 5 Design Archetypes based on campaign details (industry, pillar, intent, products).

CRITICAL LEGIBILITY DIRECTIVE:
If the post copy contains a checklist of steps, features, or dense descriptive copy (even for skincare or other B2C/D2C brands!), you MUST select the "editorial_left_bleed" archetype with layoutType="editorial_column" and requireGlassmorphism=false. This activates a premium white-to-transparent left panel gradient overlay that perfectly protects text readability against complex background details.

1. "organic_minimalist" (Best for: Skincare, Cosmetics, Wellness, Fine Jewelry, Organic food/drinks)
   - Typographic Style: Elegant display Serif (e.g., "Lora", "Playfair Display") paired with soft geometric Sans-serif ("Plus Jakarta Sans", "Inter")
   - Structural Layout: Borderless floating text overlays or lightweight rounded organic glass speech bubble reviews (.bubble-speech class). Floating check star grids (e.g. ★★★★★) and circular ingredient callouts.
   - Color Mood: Travertine stone beige, soft cream, champagne, warm rose accents.
   - Variable Mappings: Use var(--headline-color) for text, var(--accent-color) for star grids and badge accents.

2. "cyberpunk_grid" (Best for: Software, SaaS, Tech, Analytics, Fintech, AI Tools)
   - Typographic Style: Modern high-tech geometric Sans-serif (e.g., "Space Grotesk", "Outfit")
   - Structural Layout: Pinned dark semi-transparent card (.cyber-glow class) with neon accent glows. High-tech details: grid blocks, metric cards with thin neon borders, circular check circles.
   - Color Mood: Deep carbon black, slate grey, glowing neon cyan/indigo, electric ultraviolet.
   - Variable Mappings: Card container background should be var(--card-bg) with border var(--card-border). Highlights use var(--accent-color).

3. "split_comparison" (Best for: Product Battles, "Us vs. Them", Promos, Case Studies)
   - Typographic Style: Heavy bold geometric Sans-serif (e.g., "Montserrat", "Bebas Neue", "Archivo Black")
   - Structural Layout: Side-by-side or stacked split boxes comparing "Our Way/Brand" (using emerald check shields) vs. "Them/Others" (using rose cross shields). High visual contrast.
   - Color Mood: Vibrant emerald green, deep rose-red, contrast slate and pure white.
   - Variable Mappings: Header text uses var(--headline-color), comparison boxes use emerald/rose borders.

4. "editorial_left_bleed" (Best for: How-Tos, Guides, Educational Courses, Intent-based step lists)
   - Typographic Style: Traditional sophisticated Serif (e.g., "Prata", "Cinzel", "Lora")
   - Structural Layout: Full-height left side gradient panel overlaying the canvas. Uses background: linear-gradient(to right, rgba(255,255,255,0.98) 0%, rgba(255,255,255,0.94) 50%, rgba(255,255,255,0) 100%); for pristine contrast. All copy (Badge, Title, Subtitle, Numbered Steps, CTA) stacked in a perfectly left-aligned vertical column.
   - Color Mood: Paper white, charcoal grey text, luxurious gold/brass accent details.
   - Variable Mappings: Always use var(--headline-color) (dark charcoal/slate) for text and var(--accent-color) for step numbers and gold accents. Never use white text.

5. "brutalist_block" (Best for: Cafe, Beverage, Youth Fashion, Streetwear, Bold Promo deals)
   - Typographic Style: Massive ultra-bold Sans-serif (e.g., "Archivo Black", "Anton", "Bungee")
   - Structural Layout: Opaque solid backing card (.brutalist-card class) with a thick solid border and a block shadow (e.g., border: 3.5px solid var(--headline-color); box-shadow: 6px 6px 0px var(--headline-color);). Uses starbursts, warning stripe dividers, and huge CTA buttons.
   - Color Mood: High-voltage electric orange, caution yellow, bright primary colors, pure solid black.
   - Variable Mappings: Backing card uses var(--card-bg) and var(--card-border). Headlines use var(--headline-color) with massive bold styles.

📐 CANVAS DIMENSIONS: ${params.canvasDimensions ? `${params.canvasDimensions.width}px × ${params.canvasDimensions.height}px` : '1080px × 1080px'} (social media post).
This is a ${params.canvasDimensions ? (params.canvasDimensions.width === params.canvasDimensions.height ? 'SQUARE' : params.canvasDimensions.width > params.canvasDimensions.height ? 'LANDSCAPE' : 'PORTRAIT') : 'SQUARE'} format.

${slideContext}

REQUIRED CSS CLASSES (pre-injected in htmlRenderer):
- class='ad-headline'  → default 42px, weight 800, line-height 1.15
- class='ad-subtitle'  → default 18px, line-height 1.55
- class='ad-body ad-feature' → default 15px
- class='ad-badge'     → default 11px, uppercase, letter-spaced (for brand/industry tags)
- class='ad-cta'       → default 13px, bold, generous padding (for CTA buttons)

ARCHETYPE CLASS UTILITIES (pre-injected in htmlRenderer):
- class='brutalist-card' → thick borders + block shadows
- class='cyber-glow'     → modern glow container border + soft shadow
- class='bubble-speech'  → rounded review bubble with speech notch
- class='text-contrast-shield' → heavy multi-layer text drop shadow for light text on dark backgrounds
- class='text-contrast-shield-light' → heavy multi-layer text glow for dark text on light backgrounds

MANDATORY GLOBAL CSS VARIABLES RULE (DO NOT HARDCODE COLOR HEXES IN DYNAMICHTMLBLOCK):
You MUST bind all color attributes in your HTML block to the CSS variables instead of hardcoding raw hex values. This is critical so the system can safely micro-tune color contrast afterward:
- For primary text/headlines: color: var(--headline-color);
- For secondary text/subtitles: color: var(--subtitle-color);
- For features/bullets list: color: var(--subtitle-color);
- For badges/highlights/icons: color: var(--accent-color); or border-color: var(--accent-color);
- For main card container backgrounds: background: var(--card-bg);
- For main card container borders: border: 1px solid var(--card-border);
- For CTA buttons: background-color: var(--cta-bg); color: var(--cta-text);

ALIGNMENT DISCIPLINE (RIGID INNER GRID):
Maintain a strict internal typographic alignment. If text is left-aligned, anchor badges and buttons perfectly to the left. Do NOT let buttons or features float centered when text is left-aligned. Use breathing room and fashion spacing. Place the master container elegantly over the planned safe tiles:
${allowedCoordinatesStr}

AVAILABLE COMPONENTS (MIX, MATCH, AND ADAPT BASED ON THE ARCHETYPE):

1. HEADER BLOCK:
   - Brand Logo & Name Header (always place this first inside the card container):
     <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 12px;">
       <img src="$$BRAND_LOGO$$" style="width: 32px; height: 32px; border-radius: 50%; object-fit: cover;" />
       <span style="font-size: 11px; font-weight: 700; color: var(--subtitle-color); text-transform: uppercase; letter-spacing: 0.08em; font-family: 'Plus Jakarta Sans', sans-serif;">$$BRAND_NAME$$</span>
     </div>
   - Badge: <span class="ad-badge">INDUSTRY · TOPIC</span>
   - Headline: <h1 class="ad-headline" style="font-family:'Lora',serif;">Word <span class="text-brand-accent">Highlight</span> <i data-lucide="sparkles" class="text-brand-accent" style="width:24px;height:24px;vertical-align:middle;display:inline-block;"></i></h1>
   - Subtitle: <p class="ad-subtitle">Sentence description here.</p><span data-doodle="scribbleUnderline" data-doodle-color="var(--accent-color)"></span>
   - Divider: <div class="divider-accent"></div>

2. NUMBERED STEP LIST (for educational / editorial_left_bleed):
   <div style="display:flex; flex-direction:column; gap:12px; margin-top:6px;">
     <div style="display:flex; align-items:flex-start; gap:10px;">
       <span style="min-width:22px; height:22px; border-radius:50%; background:var(--accent-color); color:#fff; font-size:11px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; margin-top:2px;">1</span>
       <p class="ad-body ad-feature" style="margin:0;"><strong>Step Title</strong> description copy from CopyBlueprint.</p>
     </div>
   </div>

3. ICON CHECKLIST:
   <div style="display:flex; flex-direction:column; gap:10px; margin-top:8px;">
     <div style="display:flex; align-items:center; gap:10px;">
       <i data-lucide="check-circle" class="text-brand-accent" style="width:16px;height:16px;flex-shrink:0;display:inline-block;"></i>
       <p class="ad-body ad-feature" style="margin:0;">Feature line from CopyBlueprint.</p>
     </div>
   </div>

4. STAT BLOCK (for cyberpunk_grid / proof content):
   <div style="display:flex; align-items:center; gap:14px; margin-top:14px; padding:14px 18px; background:rgba(255,255,255,0.05); border-radius:12px; border-left:3px solid var(--accent-color);">
     <span style="font-size:2.2rem; font-weight:800; color:var(--accent-color); line-height:1;">VALUE</span>
     <p class="ad-body" style="margin:0; font-size:0.8rem; color:var(--subtitle-color);">Label description here</p>
   </div>

5. FLOATING REVIEW CARD (for organic_minimalist / testimonials):
   <div class="bubble-speech" style="padding:16px 18px; margin-top:16px;">
     <div style="display:flex; gap:2px; margin-bottom:6px; color:var(--accent-color);">★★★★★</div>
     <p style="font-size:1.1rem; font-weight:700; color:var(--headline-color); font-style:italic; margin:0; line-height:1.35;">"Quote from CopyBlueprint"</p>
     <p class="ad-body" style="margin:6px 0 0 0; font-size:0.75rem; color:var(--subtitle-color);">— Customer Attribution</p>
   </div>

6. DECORATIVE DOODLES (scatter 1-2 visually):
   <span data-doodle="starBurst" data-doodle-color="var(--accent-color)"></span>
   <span data-doodle="waveLine" data-doodle-color="var(--accent-color)"></span>

7. CTA BUTTON (always required, pinned to bottom):
   <button class="ad-cta">CTA TEXT →</button>

RULES:
- The right 54% of the canvas is the background image scene — do NOT place elements there.
- The bottom 70px is reserved for the persistent brand footer — do NOT place elements there.
- Use Tailwind utility classes freely. Do NOT use Tailwind text-size classes (text-sm, text-lg etc).
- CONTENT HIERARCHY LAW — PRIORITIZE BREATHING ROOM OVER COMPLETENESS: Do NOT blindly render every single element from the CopyBlueprint. Social ads are NOT brochures. Select only the most impactful elements. The hierarchy is: Brand Header → Badge → Headline → 1 short subtitle sentence → max 2 bullet/step items (NOT 3, NOT 4) → CTA. If the CopyBlueprint has 3+ bullets/steps, pick the best 2 and discard the rest. Leave generous whitespace between elements — at least 16px gap between sections. A sparse, well-spaced layout always outperforms a cramped one.
- For editorial_left_bleed specifically: headline font-size must NOT exceed 2.2rem (override with inline style if needed). Body copy must be 1 sentence maximum (14-16px). Max 2 numbered steps or checklist items. Generous gap between all elements (gap: 14px minimum).
- Brand Logo & Name Header: You MUST prepend the Brand Logo & Name Header template (using exact strings '$$BRAND_LOGO$$' and '$$BRAND_NAME$$') at the very top inside the card container.
- CRITICAL TESTIMONIAL RULE: If the CopyBlueprint contains a "quote" element (or is a TESTIMONIAL intent), you MUST render it as a floating speech-bubble review card using the 'bubble-speech' class. Inside this card, display 5 gold stars (★★★★★) colored in var(--accent-color), the review quote text in elegant italic quotes using var(--headline-color), and the customer name/attribution text (prefixed with "— ") in var(--subtitle-color). This card must be rendered beautifully with good padding, looking like a premium floating social proof block. Failing to display the customer review is a critical design failure.
- The dynamicHtmlBlock must be a single root <div>. Escape all double quotes with \\\\ inside the JSON.

Visual Ad Context:
- Background Image Scene Prompt: "${params.imagePrompt}"
- Target Geography: "${geography}"
- Industry Vertical: "${params.industry}"
- Target Products/Services: "${params.services.join(', ')}"
- Brand Base Color: "${params.baseColor}"
- Brand Accent Color: "${accentColor}"
- Deterministic Safe Quadrant: "${params.safestQuadrant}"
- Grayscale Background Lightness: "${params.contrastMetrics.isDarkBg ? 'Dark' : 'Light'}"
- Dominant Background Color under Text: "${avgColorName} (Hex: ${avgColorHex})"

Provided CopyBlueprint (USE THESE EXACT TEXT NODES):
\`\`\`json
${JSON.stringify(params.copyBlueprint, null, 2)}
\`\`\`
${feedbackSection}

OUTPUT FORMAT:
Output ONLY a valid JSON object matching the LayoutBlueprint schema:
{
  "designArchetype": "organic_minimalist" | "cyberpunk_grid" | "split_comparison" | "editorial_left_bleed" | "brutalist_block",
  "visual_reasoning": "1-sentence explanation of chosen archetype and grid alignment matching the post intent",
  "layoutType": "classic" | "feature_list" | "editorial_column" | "split_screen" | "liquid",
  "requireGlassmorphism": boolean,
  "fontFamily": string (e.g. "Lora", "Space Grotesk", "Montserrat", "Playfair Display", "Bebas Neue", "Archivo Black"),
  "subtitleFontFamily": "Plus Jakarta Sans" | "Inter",
  "headlineWeight": "black" | "bold" | "semibold" | "medium",
  "fontSizeScale": number (0.85 to 1.15),
  "containerPadding": "p-6" | "p-8" | "p-10" | "p-12",
  "backgroundColorOverride": string,
  "textColorOverride": string,
  "headlineColorOverride": string,
  "subtitleColorOverride": string,
  "accentColorOverride": string,
  "ctaBackgroundColorOverride": string,
  "ctaTextColorOverride": string,
  "badgeStyle": "translucent" | "solid" | "double_ring",
  "ctaIconStyle": "none" | "inline" | "circular_arrow",
  "useScriptHighlight": boolean,
  "typographyZIndex": "behind" | "in_front",
  "dynamicHtmlBlock": "<div style=\\"position: absolute; top: 0; left: 0; width: 50%; height: calc(100% - 70px); padding: 44px 40px; display: flex; flex-direction: column; justify-content: space-between; align-items: flex-start; background: var(--card-bg); border: none;\\">...[HTML with CSS variables, max 2 bullets, generous gaps]...</div>"
}
Output ONLY the raw JSON object.`;

  try {
    const completion = await callLlm({
      model: process.env.LAYOUT_DIRECTOR_MODEL || process.env.LLM_MODEL || 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'system',
          content: `You are an expert frontend developer and UI/UX designer specializing in social media ad compositing. You produce semantic HTML with inline CSS that renders pixel-perfectly in a headless Chromium browser at 1080×1080px. You always use a component-based approach: Header Block → Numbered/Feature List → Floating Callout Card → CTA. You MUST output ONLY a valid JSON object (no prose, no markdown fences) matching the LayoutBlueprint schema. The most important field is dynamicHtmlBlock — a complete, self-contained HTML string with ALL copy elements rendered.`
        },
        { role: 'user', content: prompt }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.8,
      max_tokens: 4096
    });

    let raw = completion.choices[0]?.message?.content;
    if (!raw) throw new Error('Layout Director returned empty response');
    
    // Strip markdown JSON backticks if present
    raw = raw.replace(/^```json\s*/i, '').replace(/```\s*$/i, '').trim();
    
    const blueprint = JSON.parse(raw) as LayoutBlueprint;
    logger.info(`✓ Layout Director successfully generated visual blueprint: archetype='${blueprint.designArchetype}', layoutType='${blueprint.layoutType}', font='${blueprint.fontFamily}'`);
    return blueprint;

  } catch (error: any) {
    logger.error(`Layout Director execution failed: ${error.message}. Applying programmatic fallback LayoutBlueprint.`);
    return {
      designArchetype: 'glass',
      visual_reasoning: 'Fallback layout applied due to execution error.',
      layoutType: 'classic',
      requireGlassmorphism: true,
      fontFamily: 'Plus Jakarta Sans',
      headlineWeight: 'bold',
      fontSizeScale: 1.0,
      containerPadding: 'p-8'
    };
  }
}

/**
 * A definitive programmatic decider that evaluates both LLM suggestions and raw image analysis metrics
 * (such as background local opacity override from color analysis) to decide if glassmorphism is needed.
 */
export function determineGlassmorphism(params: {
  llmRequireGlassmorphism: boolean;
  bgOpacityOverride: number;
  imagePrompt: string;
  layoutType: string;
}): boolean {
  logger.info(`Definitive glassmorphism decider: LLM suggested=${params.llmRequireGlassmorphism}, bgOpacityOverride=${params.bgOpacityOverride.toFixed(3)}`);
  return params.llmRequireGlassmorphism;
}

/**
 * Post-processes the LLM-generated dynamicHtmlBlock to adapt it to the actual generated
 * background image's local color and luminance metrics once the image is available.
 * This ensures perfect legibility for floating text and adaptive styling.
 */
export function microTuneHtmlContrast(
  htmlBlock: string | undefined,
  contrastMetrics: {
    isDarkBg: boolean;
    headlineColor: string;
    subtitleColor: string;
    averageColorHex: string;
    accentColor?: string;
  },
  requireGlassmorphism: boolean,
  layoutType: string
): string {
  if (!htmlBlock) return '';

  const isLeftBleed = layoutType === 'editorial_column' || htmlBlock.includes('linear-gradient') || htmlBlock.includes('background:linear-gradient') || htmlBlock.includes('background: linear-gradient');

  logger.info(`Micro-tuning HTML contrast via Global CSS Variables: isDarkBg=${contrastMetrics.isDarkBg}, averageColor=${contrastMetrics.averageColorHex}, requireGlassmorphism=${requireGlassmorphism}, isLeftBleed=${isLeftBleed}`);

  // 1. Resolve high-contrast colors dynamically based on background luminance
  let headlineColor = contrastMetrics.headlineColor;
  let subtitleColor = contrastMetrics.subtitleColor;
  
  if (isLeftBleed) {
    // Left gradient panel is always clean paper white/light, so text is dark charcoal/slate
    headlineColor = '#0F172A';
    subtitleColor = '#334155';
  } else {
    if (contrastMetrics.isDarkBg) {
      headlineColor = headlineColor || '#FFFFFF';
      subtitleColor = subtitleColor || '#CBD5E1';
    } else {
      headlineColor = headlineColor || '#0F172A';
      subtitleColor = subtitleColor || '#334155';
    }
  }

  // 2. Resolve card background and borders
  let cardBg = 'transparent';
  let cardBorder = 'transparent';

  if (isLeftBleed) {
    const isRightAligned = htmlBlock.includes('right:') || htmlBlock.includes('right_bleed') || htmlBlock.includes('justify-end') || htmlBlock.includes('justify-content: flex-end') || htmlBlock.includes('justify-content:flex-end');
    const direction = isRightAligned ? 'to left' : 'to right';
    cardBg = `linear-gradient(${direction}, rgba(255, 255, 255, 0.98) 0%, rgba(255, 255, 255, 0.95) 45%, rgba(255, 255, 255, 0.8) 60%, rgba(255, 255, 255, 0) 100%)`;
    cardBorder = 'transparent';
  } else if (requireGlassmorphism) {
    if (contrastMetrics.isDarkBg) {
      cardBg = 'rgba(10, 10, 20, 0.65)';
      cardBorder = 'rgba(255, 255, 255, 0.08)';
    } else {
      cardBg = 'rgba(255, 255, 255, 0.82)';
      cardBorder = 'rgba(0, 0, 0, 0.08)';
    }
  }

  // 3. Resolve premium, legibility-guaranteed CTA colors
  let ctaBg = '#0F172A';
  let ctaText = '#FFFFFF';

  if (contrastMetrics.isDarkBg && !isLeftBleed) {
    // Dark background: white button with dark text is extremely legible and premium
    ctaBg = '#FFFFFF';
    ctaText = '#0F172A';
  } else {
    // Light background: use rich dark button
    ctaBg = '#0F172A';
    ctaText = '#FFFFFF';
  }

  // We keep the accent color as provided or soft amber/indigo fallback
  const accentColor = contrastMetrics.accentColor || (contrastMetrics.isDarkBg ? '#FBBF24' : '#4F46E5');

  // 4. Construct a clean global CSS override block
  const styleOverride = `
<style>
  :root {
    --headline-color: ${headlineColor} !important;
    --subtitle-color: ${subtitleColor} !important;
    --accent-color: ${accentColor} !important;
    --card-bg: ${cardBg} !important;
    --card-border: ${cardBorder} !important;
    --cta-bg: ${ctaBg} !important;
    --cta-text: ${ctaText} !important;
  }
  
  /* Pinned contrast shields for borderless typography over organic image scenes */
  ${!requireGlassmorphism && !isLeftBleed ? `
  .ad-headline {
    text-shadow: ${contrastMetrics.isDarkBg
      ? '0px 4px 18px rgba(0,0,0,0.65), 0px 2px 8px rgba(0,0,0,0.45)'
      : '0px 4px 18px rgba(255,255,255,0.75), 0px 2px 8px rgba(255,255,255,0.55)'
    } !important;
  }
  .ad-subtitle, .ad-feature, .ad-body {
    text-shadow: ${contrastMetrics.isDarkBg
      ? '0px 2px 10px rgba(0,0,0,0.8), 0px 4px 20px rgba(0,0,0,0.5)'
      : '0px 2px 10px rgba(255,255,255,0.8), 0px 4px 20px rgba(255,255,255,0.5)'
    } !important;
  }
  ` : ''}
</style>
`;

  // Prepend the style override block to the LLM-generated HTML content
  return `${styleOverride.trim()}\n${htmlBlock}`;
}
