import { callLlm } from '../utils/llmClient';
import { createLogger } from '../utils/logger';
import { CopyBlueprint } from '../types/content';
import { DOODLES } from './svgDoodles';

const logger = createLogger({ service: 'layout-director' });

export interface LayoutBlueprint {
  designArchetype: string; // e.g. "glassmorphism", "brutalist minimal", "dark mode neon", etc.
  visual_reasoning: string; // NEW: The LLM must explicitly explain its chronological layout hierarchy (e.g. '1. Main Title placed in top_left. 2. CTA placed below title.') before writing HTML.
  layoutType: 'classic' | 'feature_list' | 'editorial_column' | 'split_screen' | 'liquid';
  requireGlassmorphism: boolean; // whether to add frosted glass card / card backplate, or let the text sit directly on the background
  fontFamily: string; // e.g. "Plus Jakarta Sans" or "Playfair Display" or "Bebas Neue"
  subtitleFontFamily?: string;
  headlineWeight: 'black' | 'bold' | 'semibold' | 'medium';
  fontSizeScale: number; // e.g. 0.85 to 1.15
  containerPadding: 'p-6' | 'p-8' | 'p-10' | 'p-12';
  backgroundColorOverride?: string; // e.g. 'rgba(15, 23, 42, 0.45)'
  textColorOverride?: string; // e.g. '#FFFFFF'
  headlineColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for the headline text
  subtitleColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for subtitles/descriptions
  accentColorOverride?: string; // Harmonious accent color chosen by the LLM for checklists, borders, icons, etc.
  ctaBackgroundColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for CTA background
  ctaTextColorOverride?: string; // Custom contrast-safe hex color chosen by the LLM for CTA button text
  badgeStyle?: 'translucent' | 'solid' | 'double_ring'; // Custom luxury visual style for features list checkmarks
  ctaIconStyle?: 'none' | 'inline' | 'circular_arrow'; // Allows the LLM to choose the premium circular arrow indicator
  useScriptHighlight?: boolean; // Instructs the compositor to load cursive scripts
  features?: string[]; // custom visual feature list items
  dynamicHtmlBlock?: string; // Full freeform HTML/CSS string generated by the LLM for website-quality ad rendering
  typographyZIndex?: 'behind' | 'in_front'; // NEW: programmatically and creatively solved Z-index stacking
  
  // Custom Dynamic Slide copy/label overrides for carousel slides
  slideHeader?: string;     // e.g. "Key", "Proven", "Experience"
  slideHighlight?: string;  // e.g. "Formulations", "Efficacy", "The Difference"
  slideSub?: string;        // e.g. "02 / 04 — BRAND POTENCY", "03 / 04 — PURE EFFICACY", "04 / 04 — READY TO GLOW"
  slideText?: string;       // e.g. "ACTIVES", "BENEFIT", "ADVANTAGE"
}


/**
 * Double-Pass Layout Director LLM Agent.
 * 
 * Performs creative layout engineering after base image generation to mathematically solve
 * Safe layout positioning, design archetype alignment, custom padding bounds, and contrast-safe coloring.
 */
export async function generateLayoutBlueprint(params: {
  imagePrompt: string;
  industry: string;
  services: string[];
  baseColor: string;
  accentColor?: string;
  geography?: string;
  safestQuadrant: string;
  quadrantScores?: Record<string, number>;
  contrastMetrics: {
    isDarkBg: boolean;
    headlineColor?: string;
    subtitleColor?: string;
    averageColorHex?: string;
    averageColorName?: string;
    detailedRegions?: {
      quadrantHeadline: any;
      quadrantSubtitle: any;
      quadrantFeatures: any;
      quadrantCta: any;
      columnHeadline: any;
      columnSubtitle: any;
      columnFeatures: any;
      columnCta: any;
    };
  };
  canvasDimensions?: { width: number; height: number };
  slideIndex?: number;
  feedback?: string;
  copyBlueprint: CopyBlueprint;
}): Promise<LayoutBlueprint> {
  logger.info(`Invoking second-pass LLM Layout Director to design ad layout (SlideIndex: ${params.slideIndex !== undefined ? params.slideIndex : 'N/A'})...`);

  // Intent classification is handled entirely by the LLM — no regex pre-classification.
  // Passing raw topic, caption, and pillar directly so the LLM can reason about intent freely.

  const headlineColor = params.contrastMetrics.headlineColor || '#FFFFFF';
  const subtitleColor = params.contrastMetrics.subtitleColor || '#E2E8F0';
  const avgColorHex = params.contrastMetrics.averageColorHex || '#121212';
  const avgColorName = params.contrastMetrics.averageColorName || 'Unknown Dark Backdrop';

  const accentColor = params.accentColor || params.baseColor || '#8B5CF6';
  const geography = params.geography || 'India';

  const slideContext = params.slideIndex !== undefined ? `
- You are designing **Slide ${params.slideIndex}** (out of a 4-slide carousel):
  * **Slide 0 (Cover)**: Captures attention, extremely bold and dramatic title. Let the background scene shine, placing the main headline beautifully in the ${params.safestQuadrant} quadrant.
  * **Slide 1 (Strengths / Core Advantages)**: Highlight 2-3 specific features, active ingredients, or core capabilities with beautiful row blocks, circular badges/icons, or checklist items.
  * **Slide 2 (Measurable Impact / Proven Efficacy)**: Showcase tangible outcomes, metrics, progress bars, or a comparison box (Us vs Them).
  * **Slide 3 (CTA / Action Card)**: High-converting closure with review star rating (★ ★ ★ ★ ★), a button, and clear closing copy.
` : `
- You are designing a standalone high-fidelity ad graphic post. Apply a premium custom layout that highlights the primary subject while rendering clean, highly readable overlays.
`;

  // Inject a subtle creative direction nudge to steer each generation toward
  // a slightly different aesthetic, while keeping things professional.
  const creativeDirections = [
    "brutalist minimal with strong geometric shapes",
    "editorial magazine spread with asymmetric layout",
    "luxury matte black with gold accents",
    "organic earth-tone with natural textures",
    "pastel dreamy with soft gradients",
    "bold neon with high contrast elements",
    "vintage retro with serif typography",
    "clean Scandinavian with lots of whitespace",
    "cyberpunk holographic with electric hues",
    "Y2K nostalgia with bubbly typography",
    "high-end cinematic with dramatic lighting",
    "surrealist floating elements with soft shadows",
    "monochrome photography with vibrant text accents",
    "glassmorphism UI with ultra-thin sleek lines",
    "elegant organic curves with soft lighting",
    "cinematic and highly polished"
  ];
  const creativeDirection = creativeDirections[Math.floor(Math.random() * creativeDirections.length)];

  // These are the CSS anchors provided to the LLM. 
  // We provide full-height columns or full-width rows so the Master Container can breathe.
  // NOTE: height is capped at calc(100% - 70px) to avoid overlapping the persistent footer bar.
  const allCoordinates: Record<string, string> = {
    top_left: 'style="position: absolute; top: 0; left: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-start;"',
    top_center: 'style="position: absolute; top: 0; left: 0; width: 100%; height: 45%; max-height: 540px; padding: 60px; display: flex; flex-direction: column; justify-content: flex-start; align-items: center;"',
    top_right: 'style="position: absolute; top: 0; right: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-end;"',
    
    middle_left: 'style="position: absolute; top: 0; left: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: center; align-items: flex-start;"',
    middle_center: 'style="position: absolute; top: 0; left: 0; width: 100%; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: center; align-items: center;"',
    middle_right: 'style="position: absolute; top: 0; right: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: center; align-items: flex-end;"',
    
    bottom_left: 'style="position: absolute; top: 0; left: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: flex-end; align-items: flex-start;"',
    bottom_center: 'style="position: absolute; bottom: 70px; left: 0; width: 100%; height: 45%; max-height: 540px; padding: 60px; display: flex; flex-direction: column; justify-content: flex-end; align-items: center;"',
    bottom_right: 'style="position: absolute; top: 0; right: 0; width: 45%; max-width: 600px; height: calc(100% - 70px); padding: 60px; display: flex; flex-direction: column; justify-content: flex-end; align-items: flex-end;"'
  };

  let allowedCoordinatesStr = '';
  if (params.quadrantScores) {
    const safeTiles = Object.entries(params.quadrantScores)
      .filter(([key, score]) => score < 0.35) // loosened threshold to find adjacent tiles
      .sort((a, b) => a[1] - b[1])
      .slice(0, 3); // MAX 3 TILES! Prevents scattering.
    
    // Always ensure the safestQuadrant is in the list
    if (!safeTiles.find(t => t[0] === params.safestQuadrant)) {
       safeTiles.unshift([params.safestQuadrant, 0]);
    }

    allowedCoordinatesStr = safeTiles.slice(0, 3).map(t => `     * ${t[0]}: ${allCoordinates[t[0]] || allCoordinates.top_left}`).join('\n');
  } else {
    allowedCoordinatesStr = `     * ${params.safestQuadrant}: ${allCoordinates[params.safestQuadrant] || allCoordinates.top_left}`;
  }

  let feedbackSection = '';
  if (params.feedback) {
    feedbackSection = `\nUSER LAYOUT FEEDBACK & DIRECTIONS (Follow these instructions to design the layout blueprint tokens appropriately):\n"${params.feedback}"\n`;
  }

  const detailedRegions = params.contrastMetrics.detailedRegions;
  let regionsInfoStr = '';
  if (detailedRegions) {
    regionsInfoStr = `
- SPECIFIC PIXEL COLORS BEHIND EACH TEXT COMPONENT SEPARATELY:
  Depending on your chosen layout structure (editorial column vs standard quadrant-based card/floating), the exact pixel background colors directly behind where each component will be placed are:
  * For Quadrant-based cards / floating layouts (standard classic, feature_list, split_screen):
    - Headline Region: ${detailedRegions.quadrantHeadline.averageColorName} (Hex: ${detailedRegions.quadrantHeadline.averageColorHex}, isDarkBg: ${detailedRegions.quadrantHeadline.isDarkBg})
    - Subtitle/Body Region: ${detailedRegions.quadrantSubtitle.averageColorName} (Hex: ${detailedRegions.quadrantSubtitle.averageColorHex}, isDarkBg: ${detailedRegions.quadrantSubtitle.isDarkBg})
    - Features List Region: ${detailedRegions.quadrantFeatures.averageColorName} (Hex: ${detailedRegions.quadrantFeatures.averageColorHex}, isDarkBg: ${detailedRegions.quadrantFeatures.isDarkBg})
    - CTA Button Region: ${detailedRegions.quadrantCta.averageColorName} (Hex: ${detailedRegions.quadrantCta.averageColorHex}, isDarkBg: ${detailedRegions.quadrantCta.isDarkBg})
  * For Column-based panels (editorial_column, editorial_left_bleed):
    - Headline Region: ${detailedRegions.columnHeadline.averageColorName} (Hex: ${detailedRegions.columnHeadline.averageColorHex}, isDarkBg: ${detailedRegions.columnHeadline.isDarkBg})
    - Subtitle/Body Region: ${detailedRegions.columnSubtitle.averageColorName} (Hex: ${detailedRegions.columnSubtitle.averageColorHex}, isDarkBg: ${detailedRegions.columnSubtitle.isDarkBg})
    - Features List Region: ${detailedRegions.columnFeatures.averageColorName} (Hex: ${detailedRegions.columnFeatures.averageColorHex}, isDarkBg: ${detailedRegions.columnFeatures.isDarkBg})
    - CTA Button Region: ${detailedRegions.columnCta.averageColorName} (Hex: ${detailedRegions.columnCta.averageColorHex}, isDarkBg: ${detailedRegions.columnCta.isDarkBg})
`;
  }

  const prompt = `You are a world-class Visual Design Director at a luxury ad agency. A highly sophisticated background image asset has been generated and pre-composed for a premium D2C brand or high-performance B2B enterprise campaign. 

YOUR SOLE MISSION IS TO ELEVATE THIS PREMIUM BACKGROUND ASSET INTO A STUNNING, MULTI-DIMENSIONAL AD MASTERPIECE. 

HOLISTIC VISUALIZATION (THINK LIKE A FINAL COMPOSITOR):
Do NOT just output random HTML text blocks blindly! Visualize the FINAL generated image. Consider what the computer vision engine has handed you (the empty grid spaces) and what the copywriter has handed you. How will these elements physically overlay on a 1080px canvas? Does the layout look disconnected? Does it obscure the product? Imagine the final rendered PNG in your mind's eye. Every absolute position and margin must serve the *final holistic visual balance* of the ad.

Do not act like a basic web form formatter that dumps text box elements one below another in a rigid vertical list, nor a chaotic generator that scatters random words in 4 different corners. Act like an elite graphic artist who treats typography as structural art. Use breathing room, elegant high-fashion typography rules, purposeful asymmetry, and luxury spacing.

🎨 CREATIVE DIRECTION FOR THIS POST: ${creativeDirection}

📐 CANVAS DIMENSIONS: ${params.canvasDimensions ? `${params.canvasDimensions.width}px × ${params.canvasDimensions.height}px` : '1080px × 1080px'} (social media post).
This is a ${params.canvasDimensions ? (params.canvasDimensions.width === params.canvasDimensions.height ? 'SQUARE' : params.canvasDimensions.width > params.canvasDimensions.height ? 'LANDSCAPE' : 'PORTRAIT') : 'SQUARE'} format.

MANDATORY TYPOGRAPHIC SIZING (CSS CLASSES ARE PRE-INJECTED — YOU MUST USE THEM):
The HTML renderer has pre-injected the following CSS classes. You MUST use these classes on every text element. You MAY override font-size with inline styles — your inline styles will win over the defaults.

REQUIRED CSS CLASSES (use these on every element):
- class='ad-headline'  → default 42px, weight 800, line-height 1.15 (override inline for bigger: style="font-size:3rem")
- class='ad-subtitle'  → default 18px, line-height 1.55 (override inline for bigger: style="font-size:1.4rem")
- class='ad-body ad-feature' → default 15px (override inline: style="font-size:0.9rem")
- class='ad-badge'     → default 11px, uppercase, letter-spaced (for tiny labels, watermarks, brand tags)
- class='ad-cta'       → default 13px, bold, generous padding (for CTA buttons)

MANDATORY CONTRAST PROTECTION (SUNBEAM SHIELD):
When placing text DIRECTLY over the background (without a frosted glass card or solid backplate), you MUST add class='text-contrast-shield' to EVERY text element. This adds a heavy multi-layer drop shadow that keeps text readable even when it crosses bright sunbeams, reflections, or white areas in the background.
- For light text on mixed dark/bright backgrounds: class='ad-headline text-contrast-shield'
- For dark text on mixed light backgrounds: class='ad-headline text-contrast-shield-light'
- If you ARE using a frosted glass backplate container, the shield is optional (the backplate provides contrast).
- DO NOT use Tailwind text-size classes (text-sm, text-lg, text-2xl etc). They are forbidden.

${slideContext}

CRITICAL AD AGENCY DESIGN PRINCIPLES:

1. COMPOSITION ELEVATION & GRID ALIGNMENT (VERTICALLY STACKED OR HORIZONTALLY SPLIT):
   - Choose the internal layout structure based on the archetype:
     * **For editorial_left_bleed**: DO NOT split horizontally! You MUST stack the Brand tag, Title, Subtitle/Description, Checklist Features, and CTA Button in a single, perfectly left-aligned vertical column. Keep alignment perfectly flush to a strict invisible left axis.
     * **For product-centric or standard cards**: You may use horizontal splitting or multi-column grids (Checklist on the left, CTA on the right) inside the card to keep things dynamic.
   - ALIGNMENT DISCIPLINE (RIGID INNER GRID): Once you group elements into a cluster (e.g. Title + Subtitle + Button in one quadrant), you MUST maintain a rigid internal typographic grid! If your text is left-aligned, anchor the button perfectly to the left. Do NOT let buttons or features float arbitrarily in the center while text is left-aligned. Messy, unanchored elements look cheap. Every element inside a cluster must align to a strict invisible axis.
   - Separate content into logical spatial clusters: place a tiny, high-letterspaced badge floating elegantly in an upper corner of your container, separate from the title, to make the layout feel spacious and alive.
   - Use high-fashion spacing: give elements "breathing room" (large margins / padding / margins) so the text card is integrated with the background negative space rather than overwhelming it.

2. CONTAINER STYLE FREEDOM (STOP DEFAULTING TO GLASSMORPHISM!):
   - Glassmorphism (frosted glass cards with backdrop-filter blur) is just ONE of many container styles. Do NOT use it by default! 
   - ACTIVELY ROTATE between these container archetypes based on the creative direction:
     * **editorial_left_bleed** (Premium Left-Side Gradient Panel): A full-height side panel on the left (\`layoutType: "editorial_column"\`, \`requireGlassmorphism: false\`) backed by a beautiful white-to-transparent (or very light brand-color-tinted to transparent) horizontal linear gradient overlay (e.g., 'background: linear-gradient(to right, rgba(255, 255, 255, 0.98) 0%, rgba(255, 255, 255, 0.95) 45%, rgba(255, 255, 255, 0.8) 60%, rgba(255, 255, 255, 0) 100%);'). All text sits directly on this gradient in a highly readable, high-contrast dark color (deep navy, charcoal, or dark slate like '#0B3C5D' or '#0F172A' matching the brand colors) with NO dropshadows. Perfect for high-fidelity B2B SaaS, learning, and professional service ads!
     * **Borderless Floating Text**: No container at all! Just large dramatic typography with strong text-shadows (text-shadow: 0 2px 8px rgba(0,0,0,0.7)) floating directly on the background. Perfect for editorial and magazine-style ads. Set requireGlassmorphism to false.
     * **Brutalist Solid Block**: Opaque, bold, geometric containers with thick borders or accent strips. No blur. Set requireGlassmorphism to false.
     * **Subtle Semi-transparent**: A very lightweight semi-transparent container (rgba background at 0.15-0.25 opacity) with NO blur, NO border. Clean and modern. Set requireGlassmorphism to false.
     * **Glassmorphism Card**: Use this sparingly — only when the creative direction explicitly mentions glass, frosted, or translucent aesthetics. Set requireGlassmorphism to true.
   - CRITICAL: If the creative direction says "brutalist", "editorial", "minimal", "floating", "cinematic", "matte", "bold", or "vintage" — you MUST NOT use glassmorphism! Use borderless text, gradient panels, or solid blocks instead.
   - ABSOLUTE CONTRAST LAW (NO ROOKIE MISTAKES): NEVER use pure white text (or light colors) on a bright, light, or sunlit background patch! If your typography is floating over a light background area, you MUST use a dark font color (e.g., #0f172a, #1e293b, or a dark shade of the brand color) OR you MUST put a dark opaque solid container behind the text! Do not rely solely on text-shadows to fix white text on a bright sunbeam.

3. DRAMATIC TYPOGRAPHY & ELITE FONT PAIRING:
   - Most premium ads use highly prominent, extra-large, bold headlines to immediately stop the scroll (e.g. style='font-size: 3rem; line-height: 1.05; font-family: Lora;').
   - You MUST select contrasting font pairings: a highly stylish display Serif for the main headings ("Lora", "Playfair Display", "Cinzel", "Prata") paired with a clean, luxury sans-serif for description nodes ("Outfit", "Inter", "Plus Jakarta Sans").
   - ELEGANT CURSIVE HIGHLIGHTS: To make the layout look premium like high-end magazine designs, you can wrap 1-2 core visual/emotional/action words in the Headline or Subtitle with a flowing, elegant cursive/handwriting highlight span: \`<span class="font-script text-accent-color">Community!</span>\` or \`<span class="font-script text-accent-color">Efficacy</span>\` or \`<span class="font-script text-accent-color">Difference</span>\`.
   - If you do this, you MUST set \`useScriptHighlight: true\` in the returned JSON so that the cursive engines are loaded.
   - CRITICAL: Render the exact copy nodes from the CopyBlueprint. Do not hallucinate or change the text. Your value is pure composition design and layout engineering.

4. SOPHISTICATED COLORING & ACCENT HARMONY (CHOOSE CONTRAST-SAFE COLORS):
   - You are explicitly requested to CHOOSE the hex colors for the text overlays and buttons to guarantee maximum visibility and premium visual appeal over the detected background color: "${avgColorName} (Hex: ${avgColorHex})" (isDarkBg: ${params.contrastMetrics.isDarkBg}).
   - Choose:
     * \`headlineColorOverride\`: The exact contrast-safe color for primary headlines. If the background under the text is dark, choose a light color (e.g. '#FFFFFF', '#F8FAFC', '#E2E8F0', soft warm cream). If the background is light/bright, choose a solid dark color (e.g. '#0F172A', '#1E293B', '#111111').
     * \`subtitleColorOverride\`: The exact contrast-safe color for subtitles and description blocks. Choose a color that is slightly softer than the headline color but retains complete contrast (e.g., if headline is '#FFFFFF', subtitle could be '#E2E8F0' or '#CBD5E1'; if headline is '#0F172A', subtitle could be '#334155' or '#475569').
     * \`accentColorOverride\`: A rich accent color for inline span highlights, checklist icons/circles, and badges (e.g. a beautiful gold '#D4AF37', warm amber, terracotta, or corporate blue/indigo '#6366F1') that contrasts perfectly with the backdrop.
     * \`ctaBackgroundColorOverride\`: The solid color for the CTA button backplate. Choose a highly prominent color that stands out yet matches the layout (e.g. clean solid black, crisp pure white, or the brand's base/accent color).
     * \`ctaTextColorOverride\`: The high-contrast text color for the CTA button text (e.g., '#FFFFFF' if the button background is dark/solid, or '#0F172A' / brand color if the button background is white).
     * \`ctaIconStyle\`: The visual icon style inside the CTA button:
       - "none": No icon inside the button.
       - "inline": A simple trailing arrow icon inside the button (e.g. →).
       - "circular_arrow": Renders a premium pill button containing a white leading circular arrow indicator (a white circle containing a colored right-facing arrow). Highly recommended for elegant, bold, and minimal layouts!
   - Make headings modern and eye-catching by wrapping core key words/percentages in dual-tone spans: e.g., "Unlock Your <span style='color: ${accentColor};'>Potential</span>" using the chosen accent color.
   - CRITICAL: NEVER use raw, highly saturated primary colors (like solid bright red or pure electric blue) for text overlays. Use curated, highly sophisticated tones from the brand visual palette that feel luxurious and blend naturally with real-world organic imagery.

5. 3D LAYERS & THE MAGICAL SANDWICH DEPTH EFFECT:
   - Under the hood, the pipeline supports realistic Z-Index sandwich stacking. If "typographyZIndex" is set to "behind", the typography sits slightly behind the prominent foreground product.
   - Plan your composition to leverage this! Align your typography so it floats majestically in the solved empty quadrant ("${params.safestQuadrant}") while peeking behind or kissing the borders of the product scene.

6. SPATIAL MAPPING & THE MASTER CONTAINER RULE (NO SCATTERING!):
   - We have run a computer-vision saliency analysis to map the "negative space" in the background.
   - The primary safe zone is "${params.safestQuadrant}".
   - THE MASTER CONTAINER: You MUST place ALL your layout elements inside a SINGLE absolute positioned master container that anchors to the safe zones. 
   - DO NOT create multiple independent absolute positioned root divs (e.g., do not put the title in one absolute div, and the button in another). Doing so destroys the internal grid alignment and scatters the layout randomly.
   - Instead, create ONE master column or row (e.g., 'position: absolute; top: 0; left: 0; width: 40%; height: 100%; display: flex; flex-direction: column; justify-content: space-between; padding: 60px;'). 
   - By using 'justify-content: space-between' inside a 100% height Master Container, you can elegantly push the Headline to the top and the CTA button to the bottom, while keeping them perfectly left-aligned together!
   - Use the following safe tiles as a guide for where to anchor your Master Container (if left tiles are safe, build a left column. If top tiles are safe, build a top bar):
${allowedCoordinatesStr}
   - IMPORTANT: Only anchor to the valid tiles listed above! DO NOT hallucinate other tiles.

7. REGIONAL ARCHITECTURAL MOTIFS:
   - Target Geography: "${geography}". Infuse subtle layout motifs matching this culture:
     * India: Thin elegant warm gold/brass accents, light marble backing colors, or marigold/terracotta highlights.
     * West (US/Canada): Industrial chic, matte graphite backing cards, borderless floating structures, high-contrast crisp typography shadows.
     * Singapore/East Asia: Biophilic structures, thin fresh bamboo-green borders, translucent glass outlines.
     * UAE: Travertine/stone warm sand beige backplates, desert warm gold tones, majestic arches.

8. PREMIUM VALUE LISTS & VERTICAL ALIGNMENT CONSTRAINTS:
   - If the ad features product features, value benefits, or ingredient callouts, do NOT throw them in a basic flat block list.
   - Build a gorgeous vertical checkmark row list using inline flexbox rules. Keep checkmark items stacked vertically in a perfect straight line for clean structure. Ensure they align beautifully with a horizontal gap and utilize custom circular icon badges.
   - Custom Luxury Checklist Badges: Choose the visual style of feature checklist badges:
     * "translucent": Accent color translucent-glass badges (default).
     * "solid": Solid accent-colored circular badges with crisp white outline icons (super modern and high-fashion).
     * "double_ring": Thin double-ring outlined circles with thin outline icons (ultra-elegant, editorial look).

9. PROMOTIONAL SALE ENFORCEMENT:
   - If a discount or offer is provided in the copy blueprint, you MUST emphasize it on the overlay! Make it the hero span or a luxurious top badge so the viewer sees the deal in The required intent is dictated by the CopyBlueprint's "intent" field. Design the layout to perfectly match this intent. For COMPARISON, use a split-screen layout. For TESTIMONIAL, use a quote block.

FORBIDDEN PATTERNS (DO NOT PRODUCE THESE — THEY ARE LAZY, CHEAP, AND WILL BE REJECTED):
❌ A glassmorphism card that spans the full width without any asymmetric offsets, floating pills, or column splits
❌ Centering EVERYTHING: title, subtitle, features, button all centered in one block
❌ Copy-pasting the same skeleton from the examples below without redesigning it for this specific post's content and intent
❌ Leaving text without explicit inline color styles

REQUIRED OUTPUT FORMAT:
Output ONLY a valid JSON object matching the following structure.
The most important field is \`dynamicHtmlBlock\` — a complete, self-contained HTML string that will be injected directly into a 1080×1080px Chromium browser canvas. This is REAL HTML rendered by a headless browser, not a description.

DYNAMICHTMLBLOCK RULES — COMPONENT TOOLKIT APPROACH:
The components below are a TOOLKIT — mix, match, and adapt them based on the creative direction and content intent. Do NOT always use the same pattern. Choose the layout archetype that best fits the creative direction assigned to this post.

---
LAYOUT ARCHETYPE A — EDITORIAL LEFT GRADIENT PANEL (best for: educational, step-by-step, B2B, professional):
Master container: white-to-transparent gradient on the left 46%, dark text, vertical column layout.
style="position:absolute; top:0; left:0; width:46%; height:calc(100% - 70px); padding:52px 44px; display:flex; flex-direction:column; justify-content:space-between; align-items:flex-start; background:linear-gradient(to right, rgba(255,255,255,0.97) 0%, rgba(255,255,255,0.93) 55%, rgba(255,255,255,0) 100%);"
Text colors: headline #0F172A, subtitle #334155, features #1E293B. NEVER use white text on this panel.

LAYOUT ARCHETYPE B — DARK CARD OVERLAY (best for: bold neon, cyberpunk, luxury dark, cinematic):
Master container: semi-opaque dark card anchored to the safe quadrant.
style="position:absolute; top:60px; left:48px; width:44%; background:rgba(10,10,20,0.82); border-radius:16px; padding:40px 36px; display:flex; flex-direction:column; gap:16px; border:1px solid rgba(255,255,255,0.08);"
Text colors: headline #FFFFFF or #F8FAFC, subtitle #CBD5E1, accent color for highlights.

LAYOUT ARCHETYPE C — FLOATING BORDERLESS TEXT (best for: editorial magazine, minimalist, vintage, organic):
No container background — text floats directly on the background with strong contrast shields.
style="position:absolute; top:0; left:0; width:46%; height:calc(100% - 70px); padding:52px 44px; display:flex; flex-direction:column; justify-content:space-between; align-items:flex-start;"
Add class="text-contrast-shield" or class="text-contrast-shield-light" to every text element based on background lightness.

---
AVAILABLE COMPONENTS (use the ones that fit your chosen archetype):

HEADER BLOCK:
- Badge: <span class="ad-badge" style="color:ACCENT_COLOR; letter-spacing:0.18em; border-left:3px solid ACCENT_COLOR; padding-left:8px;">INDUSTRY · TOPIC</span>
- Headline with accent span + icon: <h1 class="ad-headline" style="color:TEXT_COLOR; font-size:2.6rem; line-height:1.1; margin:8px 0 0 0;">Word <span style="color:ACCENT_COLOR;">Word</span> <i data-lucide="sparkles" style="width:24px;height:24px;color:ACCENT_COLOR;vertical-align:middle;"></i></h1>
- Subtitle + scribble underline: <p class="ad-subtitle" style="color:SUBTITLE_COLOR; margin:8px 0 4px 0;">Sentence.</p><span data-doodle="scribbleUnderline" data-doodle-color="ACCENT_COLOR"></span>
- Thin divider: <div class="divider-accent" style="margin:10px 0;"></div>

NUMBERED STEP LIST (for educational/how-to content):
<div style="display:flex; flex-direction:column; gap:10px; margin-top:4px;">
  <div style="display:flex; align-items:flex-start; gap:10px;">
    <span style="min-width:22px; height:22px; border-radius:50%; background:ACCENT_COLOR; color:#fff; font-size:11px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; margin-top:2px;">1</span>
    <div style="display:flex; align-items:flex-start; gap:6px;">
      <i data-lucide="droplets" style="width:14px;height:14px;color:ACCENT_COLOR;flex-shrink:0;margin-top:3px;"></i>
      <p class="ad-body ad-feature" style="color:FEATURE_COLOR; margin:0;"><strong>KeyWord</strong> full sentence from CopyBlueprint.</p>
    </div>
  </div>
</div>

ICON CHECKLIST (for product highlights, B2B features):
<div style="display:flex; flex-direction:column; gap:8px; margin-top:8px;">
  <div style="display:flex; align-items:center; gap:10px;">
    <i data-lucide="check-circle" style="width:16px;height:16px;color:ACCENT_COLOR;flex-shrink:0;"></i>
    <p class="ad-body ad-feature" style="color:FEATURE_COLOR; margin:0;">Feature text from CopyBlueprint.</p>
  </div>
</div>

STAT BLOCK (for proof/metrics content):
<div style="display:flex; align-items:center; gap:12px; margin-top:12px; padding:12px 16px; background:rgba(ACCENT_RGB,0.08); border-radius:10px; border-left:3px solid ACCENT_COLOR;">
  <span style="font-size:2rem; font-weight:800; color:ACCENT_COLOR; line-height:1;">40%</span>
  <p class="ad-body" style="color:FEATURE_COLOR; margin:0; font-size:0.75rem;">Clinically proven improvement in skin hydration</p>
</div>

FLOATING CALLOUT CARD (for quotes, testimonials, key insights):
<div style="background:rgba(ACCENT_RGB,0.07); border:1.5px solid ACCENT_COLOR; border-radius:14px; padding:14px 16px; margin-top:14px; position:relative;">
  <i data-lucide="heart" style="width:16px;height:16px;color:ACCENT_COLOR;margin-bottom:4px;display:block;"></i>
  <p style="font-size:1.05rem; font-weight:700; color:ACCENT_COLOR; font-style:italic; margin:0; line-height:1.3;">"Quote from CopyBlueprint"</p>
  <p class="ad-body" style="color:#475569; margin:6px 0 0 0; font-size:0.72rem;">Attribution line</p>
  <span data-doodle="confettiDots" data-doodle-color="ACCENT_COLOR" style="position:absolute;top:8px;right:8px;opacity:0.5;"></span>
</div>

DECORATIVE DOODLES (scatter 1-2 for visual richness):
<span data-doodle="starBurst" data-doodle-color="ACCENT_COLOR" style="display:inline-block;margin-left:4px;"></span>
<span data-doodle="waveLine" data-doodle-color="ACCENT_COLOR" style="display:block;margin:8px 0;"></span>
<span data-doodle="scribbleUnderline" data-doodle-color="ACCENT_COLOR"></span>

CTA BUTTON (always required, pinned to bottom):
<button class="ad-cta" style="background:CTA_BG; color:CTA_TEXT; border-radius:8px; border:none; display:flex; align-items:center; gap:8px; max-width:100%; word-break:break-word;">CTA TEXT →</button>

---
RULES:
- Replace ACCENT_COLOR, TEXT_COLOR, SUBTITLE_COLOR, FEATURE_COLOR, CTA_BG, CTA_TEXT with actual hex values
- The right 54% of the canvas is the AI background — do NOT place elements there
- The bottom 70px is the footer bar — do NOT place elements there
- Use Tailwind utility classes freely. Do NOT use Tailwind text-size classes (text-sm, text-lg etc)
- The HTML must be a single root <div>. Escape all double quotes with \\\\ inside the JSON string
- Render ALL elements from the CopyBlueprint — every feature, badge, statistic, and quote

EXAMPLE dynamicHtmlBlock (editorial left column with full content — copy this pattern):
The dynamicHtmlBlock must look like this — a real, complete HTML string with ALL copy elements rendered inline:

\`<div style="position: absolute; top: 0; left: 0; width: 46%; height: calc(100% - 70px); padding: 52px 48px; display: flex; flex-direction: column; justify-content: space-between; align-items: flex-start; background: linear-gradient(to right, rgba(255,255,255,0.97) 0%, rgba(255,255,255,0.93) 55%, rgba(255,255,255,0) 100%);"><div style=\\"display:flex;flex-direction:column;gap:14px;\\"><span class=\\"ad-badge\\" style=\\"color:#B45309;letter-spacing:0.18em;\\">SKINCARE ESSENTIALS</span><h1 class=\\"ad-headline\\" style=\\"color:#0F172A;font-size:2.8rem;line-height:1.1;margin:0;\\">Glowing <span style=\\"color:#D97706;\\">Morning</span> Routines</h1><p class=\\"ad-subtitle\\" style=\\"color:#334155;margin:0;\\">5 simple steps for busy Indian women to achieve healthy, glowing skin.</p><div style=\\"display:flex;flex-direction:column;gap:10px;margin-top:4px;\\"><div style=\\"display:flex;align-items:flex-start;gap:10px;\\"><span style=\\"min-width:22px;height:22px;border-radius:50%;background:#D97706;color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px;\\">1</span><p class=\\"ad-body ad-feature\\" style=\\"color:#1E293B;margin:0;\\"><strong>Cleanse</strong> with a gentle face wash to remove overnight impurities and prep your skin.</p></div><div style=\\"display:flex;align-items:flex-start;gap:10px;\\"><span style=\\"min-width:22px;height:22px;border-radius:50%;background:#D97706;color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px;\\">2</span><p class=\\"ad-body ad-feature\\" style=\\"color:#1E293B;margin:0;\\"><strong>Apply</strong> a few drops of Hyaluronic Acid Serum for an instant hydration boost.</p></div><div style=\\"display:flex;align-items:flex-start;gap:10px;\\"><span style=\\"min-width:22px;height:22px;border-radius:50%;background:#D97706;color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px;\\">3</span><p class=\\"ad-body ad-feature\\" style=\\"color:#1E293B;margin:0;\\"><strong>Lock in</strong> moisture with a nourishing Anti-Aging Cream to reduce fine lines.</p></div></div></div><button class=\\"ad-cta\\" style=\\"background:#0F172A;color:#FFFFFF;border-radius:8px;border:none;cursor:pointer;display:flex;align-items:center;gap:8px;\\">Start Your Journey →</button></div>\`

{
  "designArchetype": "editorial_left_bleed",
  "visual_reasoning": "1. Full-height left gradient panel. 2. Badge top, headline with accent span, subtitle, numbered step list. 3. CTA pinned to bottom.",
  "layoutType": "editorial_column",
  "requireGlassmorphism": false,
  "containerPadding": "p-12",
  "backgroundColorOverride": "transparent",
  "textColorOverride": "#0F172A",
  "headlineColorOverride": "#0F172A",
  "subtitleColorOverride": "#334155",
  "accentColorOverride": "#D97706",
  "ctaBackgroundColorOverride": "#0F172A",
  "ctaTextColorOverride": "#FFFFFF",
  "badgeStyle": "solid",
  "ctaIconStyle": "inline",
  "useScriptHighlight": false,
  "typographyZIndex": "in_front",
  "dynamicHtmlBlock": "<div style=\\"position: absolute; top: 0; left: 0; width: 46%; height: calc(100% - 70px); padding: 52px 48px; display: flex; flex-direction: column; justify-content: space-between; align-items: flex-start; background: linear-gradient(to right, rgba(255,255,255,0.97) 0%, rgba(255,255,255,0.93) 55%, rgba(255,255,255,0) 100%);\\">...[FULL HTML with all copy elements]...</div>"
}


Visual Ad Context:
- Background Image Scene Prompt: "${params.imagePrompt}"
- Target Geography: "${geography}"
- Industry Vertical: "${params.industry}"
- Target Products/Services: "${params.services.join(', ')}"
- Brand Base Color: "${params.baseColor}"
- Brand Accent Color: "${accentColor}"
- Deterministic Safe Quadrant: "${params.safestQuadrant}"
- Quadrant Occupancy Scores (0 = Empty, 1 = Occupied): ${JSON.stringify(params.quadrantScores || {}, null, 2)}
- Grayscale Background Lightness: "${params.contrastMetrics.isDarkBg ? 'Dark (requires light typography)' : 'Light (requires dark typography)'}"
- Dominant Background Color under Text: "${avgColorName} (Hex: ${avgColorHex})"
${regionsInfoStr}
- Resolved High-Contrast Headline Color: "${headlineColor}"
- Resolved High-Contrast Subtitle Color: "${subtitleColor}"

Provided CopyBlueprint (USE THESE EXACT TEXT NODES):
\`\`\`json
${JSON.stringify(params.copyBlueprint, null, 2)}
\`\`\`
${feedbackSection}

FINAL MANDATE: You are an award-winning Creative Director. The layout you produce MUST feel like it was designed by a real human expert at a premium agency — NOT generated by a template engine. Study the creative direction assigned to this post, study the content intent, and create something genuinely surprising and beautiful. For D2C: think Glossier, Hey Bud, Bite, Blume, Loewe. For B2B/Enterprise: think Stripe, Linear, Vercel, Notion.
If the slideIndex is defined (Slide 1, 2, or 3), design the layout specifically for that carousel position: Slide 1 = Feature showcase, Slide 2 = Proof/metrics, Slide 3 = CTA/conversion close.
Use the forbidden patterns list as a checklist — if your layout matches any of those patterns, redesign it completely before responding.

CRITICAL: You MUST include a \`dynamicHtmlBlock\` field in your JSON output. This is the most important field — it is the actual HTML that will be rendered by a headless Chromium browser at ${params.canvasDimensions ? `${params.canvasDimensions.width}×${params.canvasDimensions.height}px` : '1080×1080px'}. Write real, complete, production-quality HTML. Use the exact copy text from the CopyBlueprint. Render ALL elements from the CopyBlueprint — every feature, badge, statistic, and quote must appear in the HTML. The JSON design tokens (layoutType, fontFamily, etc.) are secondary — the \`dynamicHtmlBlock\` is the primary output.
Output ONLY the JSON object.`;

  try {
    const completion = await callLlm({
      model: process.env.LAYOUT_DIRECTOR_MODEL || process.env.LLM_MODEL || 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'system',
          content: `You are an expert frontend developer and UI/UX designer specializing in social media ad compositing. You produce semantic HTML with inline CSS that renders pixel-perfectly in a headless Chromium browser at 1080×1080px. You always use a component-based approach: Header Block → Numbered/Feature List → Floating Callout Card → CTA. You MUST output ONLY a valid JSON object (no prose, no markdown fences) matching the LayoutBlueprint schema. The most important field is dynamicHtmlBlock — a complete, self-contained HTML string with ALL copy elements rendered.`
        },
        { role: 'user', content: prompt }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.8,
      max_tokens: 4096
    });

    let raw = completion.choices[0]?.message?.content;
    if (!raw) throw new Error('Layout Director returned empty response');
    
    // Strip markdown JSON backticks if present
    raw = raw.replace(/^```json\s*/i, '').replace(/```\s*$/i, '').trim();
    
    const blueprint = JSON.parse(raw) as LayoutBlueprint;
    logger.info(`✓ Layout Director successfully generated visual blueprint: archetype='${blueprint.designArchetype}', layoutType='${blueprint.layoutType}', font='${blueprint.fontFamily}'`);
    return blueprint;

  } catch (error: any) {
    logger.error(`Layout Director execution failed: ${error.message}. Applying programmatic fallback LayoutBlueprint.`);
    return {
      designArchetype: 'glass',
      visual_reasoning: 'Fallback layout applied due to execution error.',
      layoutType: 'classic',
      requireGlassmorphism: true,
      fontFamily: 'Plus Jakarta Sans',
      headlineWeight: 'bold',
      fontSizeScale: 1.0,
      containerPadding: 'p-8'
    };
  }
}

/**
 * A definitive programmatic decider that evaluates both LLM suggestions and raw image analysis metrics
 * (such as background local opacity override from color analysis) to decide if glassmorphism is needed.
 */
export function determineGlassmorphism(params: {
  llmRequireGlassmorphism: boolean;
  bgOpacityOverride: number;
  imagePrompt: string;
  layoutType: string;
}): boolean {
  logger.info(`Definitive glassmorphism decider: LLM suggested=${params.llmRequireGlassmorphism}, bgOpacityOverride=${params.bgOpacityOverride.toFixed(3)}`);
  return params.llmRequireGlassmorphism;
}
