/**
 * Content Generation Data Contracts
 * 
 * These types define the strict shape of data flowing through the backend pipeline.
 * Used for: Database reads → Processing → API responses
 */

// ============================================================================
// INPUT CONTRACT (Data read from PostgreSQL)
// ============================================================================

/**
 * ContentInput - Raw campaign data read from database
 * 
 * Represents unvalidated input from the campaigns table.
 * Validation and normalization happen after this contract.
 */
export interface ContentInput {
  /** Business industry (e.g., "Fitness", "E-commerce") */
  industry: string;

  /** Total campaign duration in days */
  total_days: number;

  /** Number of posts per week (1-7) */
  frequency_per_week: number;

  /** Whether to include festival-specific posts */
  festival_enabled: boolean;

  /** URL to company logo image */
  logo_url: string;

  /** Font family for branding (e.g., "Roboto", "Montserrat") */
  font_style: string;

  /** Brand accent color in hex format (e.g., "#FF6B35") */
  accent_color: string;

  /** Brand base color in hex format (e.g., "#004E89") */
  base_color: string;

  /** Array of services offered by the business */
  services: string[];

  /** Target geography (e.g., "India") */
  geography: string;
}

// ============================================================================
// OUTPUT CONTRACT (API response structure)
// ============================================================================

/**
 * ContentOutput - Complete pipeline response
 * 
 * Contains everything the frontend/API consumer needs:
 * - Generated content strategy
 * - Scheduled calendar
 * - Ready-to-post content with images
 */
export interface ContentOutput {
  /** AI-generated content strategy */
  strategy: Strategy;

  /** Scheduled content calendar */
  calendar: CalendarItem[];

  /** Generated posts with captions and images */
  posts: PostItem[];
}

// ============================================================================
// STRATEGY TYPE
// ============================================================================

/**
 * Strategy - AI-generated content strategy
 * 
 * Defines the overall approach for content creation.
 * Generated by LLM based on industry and business context.
 */
export interface Strategy {
  /** Array of content themes/pillars (e.g., ["Education", "Trust", "Promotion"]) */
  content_pillars: string[];

  /** Brand tone and voice (e.g., "Professional and friendly") */
  tone: string;

  /** Call-to-action style (e.g., "Soft sell", "Direct") */
  cta_style: string;

  /** Content distribution percentages (must sum to 100) */
  content_mix: {
    /** Educational content percentage (0-100) */
    education: number;

    /** Trust-building content percentage (0-100) */
    trust: number;

    /** Promotional content percentage (0-100) */
    promotion: number;
  };
}

// ============================================================================
// CALENDAR TYPE
// ============================================================================

/**
 * CalendarItem - A single scheduled content slot
 * 
 * Represents when and what type of content should be posted.
 * Can be either regular content or festival-specific.
 */
export interface CalendarItem {
  /** Date when this should be posted (ISO string format) */
  date: string;

  /** Content pillar/theme for this post */
  pillar: string;

  /** Topic/title for this post (not full caption) */
  topic: string;

  /** Type of content (always "image" for V1) */
  content_type: string;

  /** Whether this is a festival/event post */
  is_festival: boolean;

  /** Festival/event name (if is_festival is true) */
  festival_name?: string;
}

/**
 * FestivalEvent - Festival or holiday data
 * 
 * Used to overlay festival posts on the calendar.
 */
export interface FestivalEvent {
  /** Date of the festival (ISO string) */
  date: string;

  /** Name of the festival/event */
  name: string;

  /** Category: national, religious, cultural, etc. */
  category: string;

  /** Relevance level for content */
  relevance: 'high' | 'medium' | 'low';
}

// ============================================================================
// POST TYPE
// ============================================================================

/**
 * PostItem - A complete, ready-to-publish post
 * 
 * Contains everything needed to post to social media:
 * - Caption with hashtags
 * - Generated image URL
 * - Scheduling information
 */
export interface PostItem {
  /** Unique identifier linking to calendar entry */
  entryId: string;

  /** When this post should be published */
  scheduledDate: Date;

  /** Post caption text */
  caption: string;

  /** Recommended hashtags (already formatted with #) */
  hashtags: string[];

  /** Call-to-action text (optional) */
  callToAction?: string;

  /** Public URL to generated image (hosted on S3/MinIO) */
  imageUrl: string;

  /** Metadata about content generation */
  metadata: PostMetadata;
}

/**
 * PostMetadata - Additional information about post generation
 * 
 * Useful for analytics and debugging.
 */
export interface PostMetadata {
  /** Which content pillar this post belongs to (if regular post) */
  contentPillar?: string;

  /** Which festival this celebrates (if festival post) */
  festival?: string;

  /** Timestamp when this post was generated */
  generatedAt: Date;

  /** Image generation prompt used */
  imagePrompt: string;

  /** AI model used for image generation */
  imageModel: string;
}
